### ISSUE TITLE
Combine Kong Routes for Ingress Resources

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2490] opened 2022-05-13 19:22 UTC
### Problem Statement

There's ongoing research into the Kong Gateway that shows that large configuration sizes may cause stability issues. Currently when processing `Ingress` resources (and other resources, like `HTTPRoute`) we create a route per routing rule and attach those to their respective `Kong Services`. Some of these routes can be combined into individual routes with the effect of reducing the overall configuration size, which at certain scales is expected to help with the large configuration size problem.

### Proposed Solution

- [ ] combine routes where possible in the `Ingress` parser implementation
- [ ] write an integration test that proves the route combination

### Additional information

- [ ] we must have a feature gate for this option as the change is needed by some end-users in the field immediately, but is also a large enough change that we want to be cautious about rolling it out as a default.

**Comment by mflendrich** [comment] 2022-05-13 23:21
duplicate of #2218?

**Comment by shaneutt** [comment] 2022-05-16 21:41
An image for a prototype implementation of this has been pushed to `kongbot/kubernetes-ingress-controller:hotfix-experimental-combined-routes` for testing. This implementation lacks backwards compatibility with historical route names but otherwise can significantly reduce config size under certain conditions (essentially, the end user would need to be using a very large number of paths for a single service, host, and port). The next step here is for us maintainers to talk about how we want the eventual patch to roll out in upcoming releases before we proceed with a full PR as this change is disruptive and in some ways effectively backwards incompatible (particularly with gateway metrics which hone in on routes). We should consider whether we're going to do it inline, or perhaps as a feature gated option.

**Comment by shaneutt** [comment] 2022-05-24 00:24
PR #2507 is ready for review.

**Closed** 2022-05-25 16:53 UTC
Labels: area/feature, severity/high
