### ISSUE TITLE
feature: add support for UDP proxying

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#839] opened 2020-09-11 22:21 UTC
Kong 2.2 introduces UDP proxying support. Ensure that ingress controller can configure UDP Ingress.

**Comment by m4ver1k** [comment] 2020-09-30 19:14
Can I give this a try ?

**Comment by mflendrich** [comment] 2020-12-11 11:55
#925 is a duplicate of this item but has more information on it, so closing this one.

**Closed** 2020-12-11 11:56 UTC
Labels: feature, help wanted
