### ISSUE TITLE
apiextensions.k8s.io/v1beta1 CustomResourceDefinition deprecated in v1.16+

### ISSUE THREAD

**Issue by erikhh** [Kong/kubernetes-ingress-controller#1050] opened 2021-02-25 10:48 UTC
After upgrading our EKS cluster to Kubernetes 1.19 I'm getting this deprecation warning:

```
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

We're using the https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-postgres.yaml deployment.

I tried to fix it myself, but it seems that the format changed quite a bit and I really don't understand these custom resource definitions. I can't quite work out what it's supposed to be.

**Comment by mflendrich** [comment] 2021-02-26 21:07
Duplicate of #801 

The choice of k8s api versions we've made in our manifests is intended to support the broadest possible range of present Kubernetes versions, in order to achieve working configurations for the broadest possible group of users.

We totally have the upgrade on our radar, but making that leap effectively drops support for k8s 1.14 and 1.15, which is why we haven't done this yet.

**Closed by mflendrich** 2021-02-26 21:07 UTC

**Comment by mflendrich** [comment] 2021-02-26 21:09
The recommended way forward is to ignore these deprecation warnings until Kong Ingress Controller comes with an updated set of manfiests (which will happen around the time 1.22 is released, and certainly long before EKS starts supporting 1.22)

**Comment by erikhh** [comment] 2021-03-01 10:10
Yeah alright, that makes sense. Thanks for the explanation.
