### ISSUE TITLE
Kong ingress-controller restart all the time when we upgrade the Kong version directly

### ISSUE THREAD

**Issue by yaoyao12138** [Kong/kubernetes-ingress-controller#2284] opened 2022-02-22 11:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we upgrade the Kong from an old verison 0.8 to the new version 2.5 directly in the env, the kong ingress-controller container always restart due to this crd `udpingress` lacked. Except applied this crd mannually, is there any other suggestion to fix it in Kong code? Thank you.
```
➜  ~ kc get po -A|grep kong
katamari                                           gateway-kong-544f8b74bc-hq2pg                                       1/2     CrashLoopBackOff   7          30m
katamari                                           ibm-kong-operator-65c675b488-gzbm2                                  1/1     Running            0          31m
➜  ~ kc logs gateway-kong-544f8b74bc-hq2pg -c ingress-controller
...
I0222 09:27:56.085980       1 request.go:665] Waited for 11.189621419s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/k8s.cni.cncf.io/v1?timeout=32s
time="2022-02-22T09:28:01Z" level=error msg="if kind is a CRD, it should be installed before calling Start" error="no matches for kind \"UDPIngress\" in version \"configuration.konghq.com/v1beta1\"" kind="{\"
...
```

**Comment by shaneutt** [comment] 2022-02-22 14:45
Currently we provide two explicit methods of deployment:

1. `kustomize`
2. `helm`

[As documented](https://docs.konghq.com/kubernetes-ingress-controller/2.1.x/deployment/k4k8s/#kustomize) the Helm chart is the only entirely supported production deployment method (kustomize is meant for testing and evaluation) and CRD management for Helm deployments is documented as such:

https://github.com/Kong/charts/tree/main/charts/kong#crd-management

What method are you using, and is this documentation helpful to you? Let us know how we can assist you further.

**Comment by shaneutt** [comment] 2022-02-22 14:58
It would appear now that I've found https://github.com/Kong/kong-operator/issues/74 you're using the Kong Operator, correct?

**Comment by morningspace** [comment] 2022-02-23 00:37
Hi @shaneutt exactly, we are using kong operator, and we are trying to upgrade the kong version using operator at runtime. So, we'd like to manage CRDs automatically. Do you think it's possible? I see [the doc](https://github.com/Kong/charts/tree/main/charts/kong#crd-management) mentioned that it's recommended to backup the resources and it seems manual steps are required. In our case, this may not be a big problem, because all associated custom resources are auto-generated which can be rerun after upgrade.

**Comment by shaneutt** [comment] 2022-02-23 17:03
Ok, I'm going to close this as a duplicate of https://github.com/Kong/kong-operator/issues/74, and I will respond in that issue :+1:

**Closed by shaneutt** 2022-02-23 17:03 UTC
Labels: bug, pending author feedback
