### ISSUE TITLE
TLS breaks randomly on ingress update

### ISSUE THREAD

**Issue by Ehekatl** [Kong/kubernetes-ingress-controller#603] opened 2020-04-15 17:16 UTC
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

In addition to #524 my issue seems different than those cases.
I'm using separate certificate for each SNI, no duplication, no cross namespace reference.
Some certificate are managed by certbot, some are from kubernetes secrets.

Whenever there is a change on ingress, e.g. update/delete ANY ingress resources, there is a small chance to break TLS.

**Kong Ingress controller version**
master branch with commit 17bc775, reproducible on previous version as well 

### Kubernetes version

**paste `kubectl version` output**

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: Bare metal
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04
- **Kernel** (e.g. `uname -a`): 4.15.0-70-generic
- **Others**: running with Kong 2.0.3

### What happened

Sometimes TLS breaks when update made towards other unrelated ingress/certificate.

![image](https://user-images.githubusercontent.com/7362589/79366324-8e67de00-7f7e-11ea-9bd7-81d5c658ea56.png)

In above screenshot, those configuration sync are triggered by certbot for renewing (on the right side).
Among 5 of kong pods, one of them run into issue for several times (on the left side), and only recover by next re-sync. 

### Expected behavior

TLS should always work

### Steps To Reproduce

Can't not constantly reproduce the issue, I met this a few time a day with:

1. Running some kong pods
2. Monitoring any SNI endpoint with each Pod's IP
3. Keep update/delete ingress (maybe with some certbot renewing)

**Comment by hbagdi** [comment] 2020-04-15 20:52
I'm quite certain that this is a bug in Kong and not the controller.
I'll do some tests to investigate this and get back to you.

**Comment by hbagdi** [comment] 2020-04-15 21:55
I got it to reproduce.
Here is the bug report for Kong: https://github.com/Kong/kong/issues/5789

**Comment by hbagdi** [comment] 2020-04-15 22:03
@Ehekatl What is the value of `KONG_NGINX_WORKER_PROCESSES` environment variable in your case?
If I set it to `1` then this problem goes away (it might not be an acceptable solution for all use cases).

**Comment by Ehekatl** [comment] 2020-04-16 02:14
@hbagdi Ya, we set `KONG_NGINX_WORKER_PROCESSES ` 6. 
Thanks so much for jumping on this 🎉

**Comment by hbagdi** [comment] 2020-04-28 21:34
Closing this since it is being tracked in https://github.com/Kong/kong/issues/5789. Kong 2.0.5 should contain a fix for this.

**Closed by hbagdi** 2020-04-28 21:34 UTC
Labels: needs investigation
