### ISSUE TITLE
Gateway Discovery: add support for IPv6

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#5138] opened 2023-11-09 20:18 UTC
### Problem statement

Gateway Discovery in its current form doesn't support IPv6 for the following reasons:

- ~default `ip` dns strategy doesn't work~

  ```
  2023-11-09T20:06:35Z    info    setup   Retrying kong admin api client call after error {"v": 0, "retries": "0/60", "error": "making HTTP request: Get \"https://fd00:10:244::27:8444/\": dial tcp [fd00:10:244::27]:8444: connect: connection refused"}
  ```
  
  ~It would seem that it should need an additional `[]` around the IP address but a) it seems that this is handled on the Go level already b) local testing with that added in didn't solve the issue. There has to be something else that's making this fail because `curl` from within the pod would also fail.~

  This seems to have been caused by Admin API listening only on the IPv4 interface. Setting `KONG_ADMIN_LISTEN` to `[::]:8444 ssl` (or more options if need be) makes this work.
  
  ```
  2023-11-09T20:23:45Z    info    Successfully synced configuration to Kong    {"url": "https://fd00:10:244::30:8444", "update_strategy": "InMemory", "v": 0}
  ```

- `pod` dns strategy doesn't work but might work given some changes in the code, specifically substituting the `::` and `:` to `-` in the ip address so that `fd00:10:244::2d` would yield `fd00-10-244-2d`.

  Although I wasn't able to test this because this requires a fully functional dns within the cluster and the coredns installation that I had available complained:

  ```
  [ERROR] plugin/errors: 2 fd00-10-244-2d. AAAA: dial udp [fe80::bcd0:74ff:fe40:f364%3]:53: connect: network is unreachable
  ```

- `service` dns strategy has its own problem #5110 that still has to be solved before

### Acceptance criteria

- [ ] Gateway Discovery works with IPv6 Kubernetes clusters

**Comment by rainest** [comment] 2023-11-09 20:45
Removing `http2` from the admin listen works around at least one known, but as yet unexplained issue.

The below uses KIC 2.11.1 (I was working from a customer report at that version) and Go 1.20.11 line numbers. Initial review suggests the same issue is still present on 3.0.0.

Staring at a debugger far too long shows that the initial GetRoot has no timeout, and that Golang's HTTP/2 implementation hits an infinite loop somewhere.

```
(dlv) bt
 0  0x0000000000a6edca in net/http.(*http2Transport).RoundTrip
    at net/http/h2_bundle.go:7474
 1  0x0000000000ac3ffd in net/http.(*Transport).roundTrip
    at net/http/transport.go:601
 2  0x0000000000a9adcf in net/http.(*Transport).RoundTrip
    at net/http/roundtrip.go:17
 3  0x0000000002364103 in github.com/kong/kubernetes-ingress-controller/v2/internal/adminapi.(*HeaderRoundTripper).RoundTrip
    at github.com/kong/kubernetes-ingress-controller/v2/internal/adminapi/header_roundtripper.go:29
 4  0x0000000000a365a4 in net/http.send
    at net/http/client.go:252
 5  0x0000000000a35d65 in net/http.(*Client).send
    at net/http/client.go:176
 6  0x0000000000a39e8c in net/http.(*Client).do
    at net/http/client.go:716
 7  0x0000000000a38c8f in net/http.(*Client).Do
    at net/http/client.go:582
 8  0x00000000021af26b in github.com/kong/go-kong/kong.(*Client).DoRAW
    at github.com/kong/go-kong@v0.46.0/kong/client.go:236
 9  0x00000000021af568 in github.com/kong/go-kong/kong.(*Client).Do
    at github.com/kong/go-kong@v0.46.0/kong/client.go:255
10  0x00000000021b107a in github.com/kong/go-kong/kong.(*Client).Root
    at github.com/kong/go-kong@v0.46.0/kong/client.go:397
11  0x00000000026cd315 in github.com/kong/kubernetes-ingress-controller/v2/internal/manager/utils/kongconfig.GetRoots.func1.1
    at github.com/kong/kubernetes-ingress-controller/v2/internal/manager/utils/kongconfig/root.go:219
12  0x000000000235c4d1 in github.com/avast/retry-go/v4.Do.func1
    at github.com/avast/retry-go/v4@v4.5.0/retry.go:115
13  0x000000000235d784 in github.com/avast/retry-go/v4.DoWithData[go.shape.interface {}]
    at github.com/avast/retry-go/v4@v4.5.0/retry.go:179
14  0x000000000235c3ff in github.com/avast/retry-go/v4.Do
    at github.com/avast/retry-go/v4@v4.5.0/retry.go:118
15  0x00000000026cd23d in github.com/kong/kubernetes-ingress-controller/v2/internal/manager/utils/kongconfig.GetRoots.func1
    at github.com/kong/kubernetes-ingress-controller/v2/internal/manager/utils/kongconfig/root.go:217
16  0x00000000022a5802 in golang.org/x/sync/errgroup.(*Group).Go.func1
    at golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75
17  0x0000000000478b41 in runtime.goexit
    at runtime/asm_amd64.s:1598
```

The code at https://cs.opensource.google/go/go/+/refs/tags/go1.20.11:src/net/http/transport.go;l=597-632 apparently retries HTTP/2 requests indefinitely if there is no timeout. AFAICT the `resp, err = pconn.alt.RoundTrip(req)` call always returns a `net/http.http2noCachedConnError` and then loops back around in a retry.

Packet captures from the kubelet show many sequences like [reset.pcap.gz](https://github.com/Kong/kubernetes-ingress-controller/files/13312612/reset.pcap.gz) (ignore the "retransmits", that's just due to capturing on the `any` interface): the controller connects, completes a TLS handshake, sends some app data, and then FINs the connection. The gateway does respond, but the response is RST as the controller side is already closed. I did not decrypt the stream to see the exact contents.

curl requests from the kubelet work fine over HTTP/2, suggesting no obvious issue with the Kong side.

**Comment by rainest** [comment] 2023-11-09 21:06
Naturally I stopped right before this would have become more obvious. Going to https://cs.opensource.google/go/go/+/refs/tags/go1.20.9:src/net/http/h2_bundle.go;l=7514

```

	addr := http2authorityAddr(req.URL.Scheme, req.URL.Host)
	for retry := 0; ; retry++ {
		cc, err := t.connPool().GetClientConn(req, addr)
```
The `addr` it will attempt to use is `[fd00:10:244::1e:8444]:443`: this part of the code is not bounding the address it provides to the client builder, so the `:8444` is address chunk, not a port, and the client attempts to use port 443 automatically.

Confusingly, it looks like we _are_ properly bounding the address elsewhere, so the initial connection failure logs show the correct address/port combo.

```
(dlv) p req
*net/http.Request {
	Method: "GET",
	URL: *net/url.URL {
		Scheme: "https",
		Opaque: "",
		User: *net/url.Userinfo nil,
		Host: "fd00:10:244::1e:8444",
		Path: "/",
		RawPath: "",
		OmitHost: false,
		ForceQuery: false,
		RawQuery: "",
		Fragment: "",
		RawFragment: "",},
	Proto: "HTTP/1.1",
	ProtoMajor: 1,
	ProtoMinor: 1,
	Header: net/http.Header [],
	Body: io.ReadCloser nil,
	GetBody: nil,
	ContentLength: 0,
	TransferEncoding: []string len: 0, cap: 0, nil,
	Close: false,
	Host: "fd00:10:244::1e:8444",
	Form: net/url.Values nil,
	PostForm: net/url.Values nil,
	MultipartForm: *mime/multipart.Form nil,
	Trailer: net/http.Header nil,
	RemoteAddr: "",
	RequestURI: "",
	TLS: *crypto/tls.ConnectionState nil,
	Cancel: <-chan struct {} {},
	Response: *net/http.Response nil,
	ctx: context.Context(*context.cancelCtx) *{
		Context: context.Context(*context.cancelCtx) ...,
		mu: (*sync.Mutex)(0xc000134380),
		done: (*"sync/atomic.Value")(0xc000134388),
		children: map[context.canceler]struct {} [],
		err: error nil,
		cause: error nil,},}
(dlv) p addr
"[fd00:10:244::1e:8444]:443"
```

**Comment by rainest** [comment] 2024-01-18 01:35
https://github.com/Kong/kubernetes-ingress-controller/pull/5139 did what it was intended to do, but the chart did not bind to IPv6 by default and did not let you override the admin listen addresses without manually setting the `KONG_ADMIN_LISTEN` envvar (the generated envvar from the templates always used v4 and ignored the hidden override in values.yaml).

Current chart releases with a fixed image show the controller correctly using a bracket-bounded address, but it doesn't matter because there's no listen there:

```
16:13:47-0800 esenin $ helm install ana kong/ingress                                             
...
16:14:04-0800 esenin $ kubectl get po
NAME                              READY   STATUS    RESTARTS   AGE
ana-controller-54dff8b895-xpzjq   0/1     Running   0          17s
ana-gateway-5d4687668c-7bg88      0/1     Running   0          17s
16:14:21-0800 esenin $ kubectl logs ana-controller-54dff8b895-xpzjq| tail -5
...
2024-01-18T00:16:06Z	info	setup	Retrying kong admin api client call after error	{"v": 0, "retries": "50/60", "error": "making HTTP request: Get \"https://fd00:10:244::7:8444/\": dial tcp [fd00:10:244::7]:8444: connect: connection refused"}

16:17:57-0800 esenin $ helm install ana kong/ingress --set controller.ingressController.image.repository="kong/nightly-ingress-controller" --set controller.ingressController.image.tag="nightly" --set controller.ingressController.image.effectiveSemver=3.1.0
...
16:18:23-0800 esenin $ kubectl get po
NAME                             READY   STATUS    RESTARTS   AGE
ana-controller-5f75c75d4-l7gwp   0/1     Running   0          16s
ana-gateway-5d4687668c-h5r2q     0/1     Running   0          16s
16:18:39-0800 esenin $ kubectl logs ana-controller-5f75c75d4-l7gwp|tail -5
...
2024-01-18T00:19:17Z	info	setup	Retrying kong admin api client call after error	{"v": 0, "retries": "48/60", "error": "making HTTP request: Get \"https://[fd00:10:244::9]:8444/\": dial tcp [fd00:10:244::9]:8444: connect: connection refused"}
```

https://github.com/Kong/charts/pull/986 uses IPv6 by default and lets you override admin if desired, but this does not align with upstream Kong defaults.

**Comment by markusleh** [comment] 2024-01-18 10:56
I have a IPv6-only cluster and can confirm that everything works with following values:
```
controller:
  proxy:
    address: "[::]"

  ingressController:
    image:
      repository: "kong/nightly-ingress-controller" 
      tag: "nightly" # currently helm chart does not install new kongvaults.configuration.konghq.com, but e.g. 2023-12-25 works
      effectiveSemver: 3.5.0
    admissionWebhook:
      address: "[::]"

gateway:
  proxy:
    address: "[::]"

  status:
    address: "[::]"

  admin:
    address: "[::]"
```
I would like to see dual stack being enabled by default as per [Kong/charts#986](https://github.com/Kong/charts/pull/986). I could not easily find documentation how to configure the listen address only (as opposed to setting env values directly) as I've done above. Getting everything to listen to ipv6 like this is quite cumbersome.

**Comment by rainest** [comment] 2024-01-19 20:58
Closing based on findings in https://github.com/Kong/charts/pull/986. That will effectively resolve this across config and implementation, but won't auto-close this because it's a chart PR.

**Closed by rainest** 2024-01-19 20:58 UTC
Labels: bug
