### ISSUE TITLE
Hmac-auth crash

### ISSUE THREAD

**Issue by SamPeng87** [Kong/kubernetes-ingress-controller#543] opened 2020-02-18 07:15 UTC
#174 # Summary
if i create hmac-auth type secret and used in KongConsumer,ingress-controller will crash

**Kong Ingress controller version**
0.7.1

**Kong or Kong Enterprise version**

### Kubernetes version
1.14(in eks)
**paste `kubectl version` output**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:45Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened
plugin yaml
```apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: api-hmac-auth
  namespace: platform
config:
  enforce_headers:
    - x-date
  clock_skew: 300
  algorithms:
    - hmac-sha256
plugin: hmac-auth
```

create secret
```
kubectl create secret generic echoserver-hmac-apikey- \
  --from-literal=kongCredType=hmac-auth \
  --from-literal=key=123456 -n platform
```

create consumer
```
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: echoserver-api-hmac
  namespace: platform
username: echoserver-hmac
credentials:
  - echoserver-hmac-apikey
```

that will crash
```
I0218 07:11:34.523513       1 main.go:407] Creating API client for https://10.100.0.1:443
I0218 07:11:34.535451       1 main.go:451] Running in Kubernetes Cluster version v1.14+ (v1.14.9-eks-c0eccc) - git (clean) commit c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2 - platform linux/amd64
I0218 07:11:34.593761       1 main.go:187] kong version: 2.0.1
I0218 07:11:34.593795       1 main.go:196] Kong datastore: postgres
I0218 07:11:34.938926       1 controller.go:224] starting Ingress controller
I0218 07:11:34.944596       1 status.go:201] new leader elected: gateway-kong-69b8c9694d-kscds
I0218 07:13:03.336409       1 status.go:201] new leader elected: gateway-kong-69b8c9694d-d4dd5
E0218 07:13:03.398380       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 174 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x142a600, 0x2229630)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:51 +0x82
panic(0x142a600, 0x2229630)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/hbagdi/deck/file.(*stateBuilder).ingestHMACAuths(0xc000f6d9f0, 0xc000fcddc0, 0x1, 0x1, 0x1, 0xc000fcddc0)
        /go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/builder.go:264 +0x408
github.com/hbagdi/deck/file.(*stateBuilder).consumers(0xc000f6d9f0)
        /go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/builder.go:181 +0xafd
github.com/hbagdi/deck/file.(*stateBuilder).build(0xc000f6d9f0, 0x0, 0x0, 0x4)
        /go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/builder.go:56 +0x124
github.com/hbagdi/deck/file.Get(0xc000b7eb60, 0xc000f3ae00, 0x2, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/reader.go:51 +0x130
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).onUpdateDBMode(0xc0000d3340, 0xc000b7eb60, 0x13c6960, 0xc000f643c0)
        /kong-ingress-controller/internal/ingress/controller/kong.go:161 +0x1c4
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).OnUpdate(0xc0000d3340, 0xc000e6ca00, 0x0, 0x0)
        /kong-ingress-controller/internal/ingress/controller/kong.go:63 +0x26c
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).syncIngress(0xc0000d3340, 0x149a360, 0xc000e749a0, 0xc0140dd8a9, 0x4b5cb2770198)
        /kong-ingress-controller/internal/ingress/controller/controller.go:117 +0x1fa
github.com/kong/kubernetes-ingress-controller/internal/ingress/task.(*Queue).worker(0xc00035efc0)
        /kong-ingress-controller/internal/ingress/task/queue.go:111 +0x2df
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0004ad7a8)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000f6dfa8, 0x3b9aca00, 0x0, 0x1, 0xc0034b9da0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88
github.com/kong/kubernetes-ingress-controller/internal/ingress/task.(*Queue).Run(0xc00035efc0, 0x3b9aca00, 0xc0034b9da0)
        /kong-ingress-controller/internal/ingress/task/queue.go:59 +0x6b
created by github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).Start
        /kong-ingress-controller/internal/ingress/controller/controller.go:232 +0xe8
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11ac4a8]

goroutine 174 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:58 +0x105
panic(0x142a600, 0x2229630)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/hbagdi/deck/file.(*stateBuilder).ingestHMACAuths(0xc000f6d9f0, 0xc000fcddc0, 0x1, 0x1, 0x1, 0xc000fcddc0)
        /go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/builder.go:264 +0x408
github.com/hbagdi/deck/file.(*stateBuilder).consumers(0xc000f6d9f0)
        /go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/builder.go:181 +0xafd
github.com/hbagdi/deck/file.(*stateBuilder).build(0xc000f6d9f0, 0x0, 0x0, 0x4)
        /go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/builder.go:56 +0x124
github.com/hbagdi/deck/file.Get(0xc000b7eb60, 0xc000f3ae00, 0x2, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/reader.go:51 +0x130
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).onUpdateDBMode(0xc0000d3340, 0xc000b7eb60, 0x13c6960, 0xc000f643c0)
        /kong-ingress-controller/internal/ingress/controller/kong.go:161 +0x1c4
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).OnUpdate(0xc0000d3340, 0xc000e6ca00, 0x0, 0x0)
        /kong-ingress-controller/internal/ingress/controller/kong.go:63 +0x26c
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).syncIngress(0xc0000d3340, 0x149a360, 0xc000e749a0, 0xc0140dd8a9, 0x4b5cb2770198)
        /kong-ingress-controller/internal/ingress/controller/controller.go:117 +0x1fa
github.com/kong/kubernetes-ingress-controller/internal/ingress/task.(*Queue).worker(0xc00035efc0)
        /kong-ingress-controller/internal/ingress/task/queue.go:111 +0x2df
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0004ad7a8)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000f6dfa8, 0x3b9aca00, 0x0, 0x1, 0xc0034b9da0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88
github.com/kong/kubernetes-ingress-controller/internal/ingress/task.(*Queue).Run(0xc00035efc0, 0x3b9aca00, 0xc0034b9da0)
        /kong-ingress-controller/internal/ingress/task/queue.go:59 +0x6b
created by github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).Start
        /kong-ingress-controller/internal/ingress/controller/controller.go:232 +0xe8
```

but I change kongCredType is key-auth.is fine.

**Comment by hbagdi** [comment] 2020-02-18 17:43
You are not supplying the right credentials needed to HMAC auth.
Please supply username and secret: https://docs.konghq.com/hub/kong-inc/hmac-auth/#create-a-credential

The controller should guard against this user, please use Admission Controller to avoid this problem.

**Comment by hbagdi** [comment] 2020-04-28 21:33
This is a duplicate of https://github.com/Kong/kubernetes-ingress-controller/issues/550 so closing this.

**Closed by hbagdi** 2020-04-28 21:33 UTC
Labels: pending author feedback
