### ISSUE TITLE
Kong 1.0 support and mesh

### ISSUE THREAD

**Issue by MilanDasek** [Kong/kubernetes-ingress-controller#214] opened 2018-12-21 07:14 UTC
Hi,

I would like to ask when we can expect Kong 1.0 compatibility and introducing service mesh feature in Kong Ingress (if that makes sense).

Thank you

Milan

**Comment by hbagdi** [comment] 2018-12-21 17:36
We're actively working for Kong 1.0 support and it has already landed in the `next` git branch of this repository so expect a release soon (few days).

Service mesh integration is in plans as to how it will integrate with Ingress Controller.
Is there a specific feature or integration that you've in mind?

**Comment by MilanDasek** [comment] 2018-12-29 09:53
I am wondering how will be mesh integrated into ingress. I am looking (except other features) for network security feature where we could define which pod/service can communicate internally with others (security rules, authentication, authorization,...) I don't have any particular use case now, just looking around. I also looked at Kong ingress presentation where it was also mentioned you're looking how to integrate mesh into this solution.

**Comment by pgold30** [comment] 2019-01-08 15:44
Is there an eta or workaround to make ingress work with kong v1.0 im getting error 

`[[kong-ingress-controller-87c7ff5f8-mbnwp] E0108 15:34:47.514069       6 controller.go:131] unexpected failure updating Kong configuration: 
[kong-admin-7f9df4c448-b99b2] 100.124.0.26 - - [08/Jan/2019:15:34:47 +0000] "GET /snis/web.staging.XXX.XXX.team HTTP/1.1" 200 167 "-" "Go-http-client/1.1" 
[kong-ingress-controller-87c7ff5f8-mbnwp] syncing targets: json: cannot unmarshal number 154XX8185.15 into Go struct field Upstream.created_at of type int64 `

**Comment by hbagdi** [comment] 2019-01-08 15:48
> Is there an eta or workaround to make ingress work with kong v1.0

It should be out in next couple days or, latest by the end of this week.

**Comment by pgold30** [comment] 2019-01-10 14:03
@hbagdi  is this fixed in the release 0.3.0 ? I updated and the issue is still there

**Comment by hbagdi** [comment] 2019-03-04 17:16
Closing this since 0.3.0 adds in support for Kong 1.0.

**Closed by hbagdi** 2019-03-04 17:16 UTC

**Comment by MilanDasek** [comment] 2019-03-16 13:17
@hbagdi

Is there a simple documentation how we can start using ingress and mesh together?

I mean like quick start with yaml examples how to setup mesh environment with service A, B and Kong behind.

thanks
