### ISSUE TITLE
 Kong ingress https://test.example.com/process/vehicle: 401 Unauthorized", error: null } 

### ISSUE THREAD

**Issue by bakuppus** [Kong/kubernetes-ingress-controller#624] opened 2020-04-26 09:38 UTC
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

 Using Kong ingress with Letsencrypt,  all api calls getting error as  https://test.example.com/process/vehicle: 401 Unauthorized", error: null } , Keycloak auth token header was unauthorized, but in "Authorization" is authorized 

**Kong Ingress controller version**
Kong Ingress controller
  Release:    0.8.1
  Build:      8fcab9f
  Repository: git@github.com:kong/kubernetes-ingress-controller.git
  Go:         go1.14.1

**Kong or Kong Enterprise version**

### Kubernetes version

Client Version: v1.14.10
Server Version: v1.14.10-gke.27

### Environment

- **Cloud provider or hardware configuration**: GCP
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened

Keycloak has generated token, which is assigned to "Authorization" is 200,
however, "Proxy-Authorization" is 401 {"message":"Unauthorized"}

### Expected behavior
status: 200

### Steps To Reproduce

1.
2.
3.
4.

**Comment by hbagdi** [comment] 2020-04-28 21:49
This is a duplicate of https://discuss.konghq.com/t/kong-ingress-https-test-example-com-process-vehicle-401-unauthorized-error-null/6154/2.
Please do not cross post. Closing this.

**Closed by hbagdi** 2020-04-28 21:49 UTC
