### ISSUE TITLE
Fix gateway API conformance tests for GWAPI 0.6.0

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#3305] opened 2022-12-23 06:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

After having bumped the Gateway API to 0.6.0, the following conformance tests have been [disabled](https://github.com/Kong/kubernetes-ingress-controller/blob/1084eb60d52bd89d7f852abce70d186e8bb0562c/test/conformance/gateway_conformance_test.go#L94-L104) and need to be fixed in order to be executed again at every CI run:

- [x] `GatewayInvalidRouteKind`
- [x] `GatewayInvalidTLSConfiguration`
- [x] `GatewaySecretReferenceGrantAllInNamespace`
- [x] `GatewaySecretReferenceGrantSpecific`
- [ ] `HTTPRouteHeaderMatching`
- [x] `HTTPRouteObservedGenerationBump`

### Acceptance Criteria

- [ ] All the aforementioned tests are enabled again and run successfully

**Comment by randmonkey** [comment] 2022-12-23 07:04
0.6.0 added `programmed` into listener condition types and condition reasons, and some conformance tests checks for this condition.

**Comment by randmonkey** [comment] 2022-12-23 07:20
related issues:
- https://github.com/Kong/kubernetes-ingress-controller/issues/3228 make supported route to consistent with upstream

**Comment by rainest** [comment] 2023-02-22 23:54
I've reviewed the header matching issue and am not sure we have a good option short of changing our gateway router tiebreaker behavior. The new test added in https://github.com/kubernetes-sigs/gateway-api/pull/1370 makes the single test HTTPRoute's ruleset this:

```
[2]
    matches:
    - headers:
      - name: version
        type: Exact
        value: two
...
[4]
    matches:
    - headers:
      - name: color
        type: Exact
        value: blue
      path:
        type: PathPrefix
        value: /
    - headers:
      - name: color
        type: Exact
        value: green
```

The corresponding spec language is https://github.com/kubernetes-sigs/gateway-api/blob/a3f769e5c690546140b6b9f0db5aea4d766b8f68/apis/v1beta1/httproute_types.go#L161-L163, i.e. that (ignoring higher-precedence tiebreakers that only apply when there are multiple HTTPRoutes) the lowest rule by array index wins.

KIC generates the following routes (among others) from the test HTTPRoute's rules:

```
$ curl -s 172.22.0.100:8001/routes/a1193384-1f5a-51c7-96a5-a9aae8ba7bc4 | jq
{
  "hosts": null,
  "created_at": 1677103911,
  "name": "httproute.gateway-conformance-infra.header-matching.3.0",
  "headers": {
    "color": [
      "blue"
    ]
  },
  "paths": [
    "/"
  ],
  "regex_priority": 0,
  "service": {
    "id": "3f637fd5-d492-5c33-b9e4-2b5925270c9c"
  },
  "id": "a1193384-1f5a-51c7-96a5-a9aae8ba7bc4",
}

$ curl -s 172.22.0.100:8001/routes/76b4eda4-ea3f-5212-8837-c58f5e6afed9 | jq
{                                                                                           
  "hosts": null,
  "created_at": 1677103911,
  "name": "httproute.gateway-conformance-infra.header-matching.1.0",
  "headers": {
    "version": [
      "two"
    ]
  },
  "paths": [
    "/"
  ],
  "regex_priority": 0,
  "service": {
    "id": "809e9da2-9a53-5e72-b3a2-71ba24da5aed"
  },
  "id": "76b4eda4-ea3f-5212-8837-c58f5e6afed9",
}
```
The test request ambiguously matches either rule because it includes both a version and color header with values matching the rule header matches, and includes nothing that violates a rule match requirement.

```
p tc.Request.Headers
map[string]string [
	"Version": "two", 
	"Color": "blue", 
]

15:34:41-0800 esenin $ curl -sv 172.22.0.102 -H "Version: two" -H "Color: blue" -H "kong-debug: true" 2>&1 | grep -E "pod|Kong-" 
< Kong-Route-Id: a1193384-1f5a-51c7-96a5-a9aae8ba7bc4
< Kong-Route-Name: httproute.gateway-conformance-infra.header-matching.3.0
< Kong-Service-Id: 3f637fd5-d492-5c33-b9e4-2b5925270c9c
< Kong-Service-Name: httproute.gateway-conformance-infra.header-matching.0
 "pod": "infra-backend-v1-dd884d67c-kwdbt"
```

These routes have identical hosts and paths, and so Kong's router has [no meaningful criteria it can use to break a tie](https://docs.konghq.com/gateway/latest/how-kong-works/routing-traffic/#matching-priorities). The router thus falls back to its [timestamp tiedbreaker](https://github.com/Kong/kong/blob/f24fbd8288f5bde0962d9c36fa827d9a9d19160a/kong/router/traditional.lua#L692-L694). The timestamps are also identical (it's DB-less, everything is created at the same time), so this actually relies on the (maybe) arbitrary, but consistent order of routes returned by DB-less entity queries: whichever route ends up on the left of the comparison, since `1677103911 < 1677103911 == false`.

There are a few approaches we could take here:

- Use names as a tiebreaker in the Kong router if `r1.route.created_at == nil and r2.route.created_at`. Our existing name generation would then meet the spec in that tiebreaker. However, this may cause unexpected changes for existing configurations, because users may unknowingly rely on the de facto query order tiebreaker for a first route whose name has higher alpha order than the second ambiguous route. Given that DB-less timestamps are a poor tiebreaker (because they're all identical), however, this change may make sense with a warning in release notes.
- Refactor the KIC parser to always add HTTPRoute rules to the Kong route list in the order they appear in the HTTPRoute. I have no idea what controls their order now, but it's apparently consistently not the HTTPRoute rule order for the above at least. This only works for DB-less, as Postgres has no control over order and Postgres route timestamps _will_ differ and hit that tiebreaker instead.
- Comedy option make everything a regex and carefully construct regex priorities matching the spec. This would probably cause lots of unexpected behavior for existing configurations.

Adding name tiebreakers is probably also important for spec requirements _not_ checked by this test, as other tiebreaker rules in the spec rely on the origin resource name. The rule checked here only matters if you need to break ties between rules in the same HTTPRoute. If you have a tie between different HTTPRoute rules, the spec instead requires using whichever has the lower HTTPRoute `namespace/name` alpha order (our name generation would comply with this if we add the tiebreaker).

**Comment by shaneutt** [comment] 2023-02-23 14:22
If I'm reading this right, it sounds like the improved tiebreaker behavior is really the way to go to create consistency.

Due to the sensitivity towards existing deployments, but also wanting to be able to pass conformance as soon as feasible: perhaps this is a situation where it would make sense to add the new behavior behind a feature gate, allowing us to enable that for conformance tests now, and in time graduate that to the default behavior (perhaps in v3)?

**Comment by rainest** [comment] 2023-02-27 22:12
The change would be in the gateway. They don't really have feature gates per se, though you could approximate it with a kong.conf setting.

**Comment by mlavacca** [comment] 2023-03-02 17:54
closing as the last conformance test has been moved to #3651

**Closed by mlavacca** 2023-03-02 17:54 UTC
Labels: area/gateway-api
