### ISSUE TITLE
Nil targets from balancer and service name resolution failed in db-less mode when use named port

### ISSUE THREAD

**Issue by Ehekatl** [Kong/kubernetes-ingress-controller#560] opened 2020-02-29 16:43 UTC
### Summary

After upgrade from 1.4.2 to 2.0.2, our service went down after a while because of `resolution failed: dns server error: 3 name error.`
When I trace down, I found several issue related to this problem:

- `get_balancer` fail in our prod env after upgradation
- it fall back to dns resolution and would never recover
- resolution fail because it use wrong service name when use named port in ingress
e.g.
<img width="419" alt="Screen Shot 2020-03-01 at 12 35 22 AM" src="https://user-images.githubusercontent.com/7362589/75611329-972e5d00-5b54-11ea-9e08-e70a27351e12.png">

![Screen Shot 2020-03-01 at 12 34 35 AM](https://user-images.githubusercontent.com/7362589/75611436-84685800-5b55-11ea-9370-c8075def505a.png)

kong would treat named port as part of service name when synced by ingress-controller
and Ooops...

it generate the same target service name on 1.4.2 but seems it always able to get target from balancer, so the problem never trigger before.

### Steps To Reproduce

Can't reproduce get balancer failure unless put in our prod env (tried bench tools...)
but for the resolution problem:

1. create a ingress with named servicePort (e.g. `http` instead of 80)
2. you got the problematic service name

### Additional Details & Logs

You can check the details of dns failure I posted in Kong/kong#5455

**Comment by Ehekatl** [comment] 2020-03-07 05:27
@hbagdi correction, actually all services are not resolvable, no matter use named port or not
![75611436-84685800-5b55-11ea-9370-c8075def505a](https://user-images.githubusercontent.com/7362589/76137356-f7eaf780-6076-11ea-856c-85f870a862b5.png)

Maybe this was exepected if all targets are get from upstream endpoints？
I think the real problem is why `get_balancer` sometimes fail after upgrade

**Comment by bungle** [comment] 2020-03-17 11:16
@Ehekatl, have you checked this comment:
https://github.com/Kong/kong/issues/5455#issuecomment-599641643

**Comment by Ehekatl** [comment] 2020-03-19 10:17
@bungle tried without lucky

and I also suspect there is a problem with kong ingress controller when updating upstream endpoint.
In my other issue, after upgrade from 1.4.2 to higher version, once the dns issue happen, it's there until I remove the problematic pod. (doesn't seems related to ingress controller, because no log & apply ingress change to trigger sync won't help)

But even with 1.4.2, I still got `failed to get target from ring balancer` sometime, it can recover automatically upon on next re-sync, or any modification to an ingress. To me it feels like something goes wrong with deck

**Comment by HsinHeng** [comment] 2020-03-25 08:34
version higher than 1.4.2, i got the same problem.
however, I am not got "failed to get target from ring balancer".
hope to solve problem.

**Comment by Ehekatl** [comment] 2020-04-08 16:18
@hbagdi despite the cause of this issue. I think the current design is a bit risky.
I can think many cases where ingress controller fail to update the target, would be nice if it can fall back to DNS resolution properly.

**Comment by Ehekatl** [comment] 2020-04-14 11:26
@hbagdi any downside for changing `upstreamName := service.Backend.Name + "." + service.Namespace + "." + service.Backend.Port.String() + ".svc"` to `upstreamName := service.Backend.Name + "." + service.Namespace + ".svc"` ?

**Comment by hbagdi** [comment] 2020-04-14 23:36
Yes. There can be services with multiple ports that are exposed via Kong.

Does that change fix any issue?

**Comment by Ehekatl** [comment] 2020-04-15 05:11
@hbagdi not necessarily fix, but I’m thinking there might be some edge case that break upstream.

e.g. connection to api server was temporarily broken while kong ingress controller receive endpoint update, it will delete then add new targets right? This may leave empty upstream.

Not sure if that’s the root cause, but this is happening from time to time.
it would be a lot more reliable if kong were able to resolve upstream when it’s empty/nil.

**Comment by hbagdi** [comment] 2020-04-20 21:51
If you don't mind using kube-proxy as a middle hop, then you can configure kong to use core-DNS always and then kube-proxy takes care of routing/load-balancing.

**Comment by swagat16** [comment] 2020-05-06 17:08
> If you don't mind using kube-proxy as a middle hop, then you can configure kong to use core-DNS always and then kube-proxy takes care of routing/load-balancing.

We are also facing a similar issue, could you please point me on how to configure Kong to use core dns   always ?

**Comment by HsinHeng** [comment] 2020-05-07 04:14
Does Kong 2.0.4 fix the issue?
I upgrade to Kong:2.0.4 and monitor it.

https://github.com/Kong/kong/issues/5455

But it seems that the fixed PR cause other issue in 2.0.4..

**Comment by hbagdi** [comment] 2020-05-08 16:48
Re-opened the issue. Please share error-logs and other relevant on the linked issue.

**Comment by carnei-ro** [comment] 2020-05-09 00:32
2.0.4 does not to include this PR https://github.com/Kong/kong/pull/5831

**Comment by carnei-ro** [comment] 2020-05-25 20:38
Neither the PR for version 2.1.0.
We are facing this problem in the production environment, and we had to rollback our upstreams configurations to "regular services".
We are really eager to have it working.

**Comment by hishamhm** [comment] 2020-05-26 18:40
@carnei-ro That PR is not in because it caused other errors in the `next` branch, and the team agreed it wasn't an ideal solution for `master` either. 

The balancer code in `next` (and by extension 2.1.0-alpha1) contains many changes, plus we pushed fixes to the DB-less configuration loading logic, which together may cause the issue to not happen in the 2.1 branch. 

We haven't had confirmation from any users that the issue persists in 2.1.0-alpha1 (so it may be fixed already!), but we continue to investigate this, and if you have any info, please let us know!

**Comment by carnei-ro** [comment] 2020-05-29 21:08
@hishamhm  we could reproduce once, I've recorded the to explain the scenario https://www.youtube.com/watch?v=w69NekUyRCk

**Comment by hbagdi** [comment] 2020-09-11 21:47
This should be fixed with newer versions of Kong. Please re-open if this is still an issue.

**Closed by hbagdi** 2020-09-11 21:47 UTC
Labels: bug

**Comment by scirner22** [comment] 2021-01-17 04:05
@hbagdi what minimum versions of kong/kong-ingress-controller fix this problem? We moved to 2.1.4 due to https://github.com/Kong/kong/pull/5831 talking about fixing this in `2.1.0` and @hishamhm also mentioning `2.1.0-alpha1` above. Note: we are running kong in db-mode.

Separate from all of the related issues to this mentioning why `balancer` can possibly be null sometimes, I'm confused why the fallback isn't able to resolve to a valid name when kong is running in k8s? Here's an example of the 3 name error that we get.

```
(short)service-application-kong.apps.80.svc:(na)
service-application-kong.apps.80.svc.kong.svc.cluster.local:33
service-application-kong.apps.80.svc.svc.cluster.local:33
service-application-kong.apps.80.svc.cluster.local:33
...
```

Two examples that would have worked are below, but the fallback never tries these

```
service-application-kong.apps
service-application-kong.apps.svc
```

**Comment by jiachinzhao** [comment] 2022-03-31 10:45
> is there any processes, we have encountered the same issue. the only resolution is delete kong pod which is

**Comment by jiachinzhao** [comment] 2022-03-31 10:46
@scirner22 
is there any processes, we have encountered the same issue.
the only resolution is delete kong pod which had error.

**Comment by shaneutt** [comment] 2022-03-31 13:36
@jiachinzhao it sounds like you're using a version zero release of the ingress controller, which are significantly old at this point and no longer officially supported. I'm curious, have you checked whether this issue persists on a modern supported version of the ingress controller? (at the time of writing, `v2.2.1` is the current stable).
