### ISSUE TITLE
Kong Ingress Controller not installing on Minikube

### ISSUE THREAD

**Issue by tobiolalusi** [Kong/kubernetes-ingress-controller#1176] opened 2021-04-11 19:37 UTC
### Summary

I've been trying to install the Kong Ingress Controller on my minikube cluster. I've tried installing both via the YAML and Helm, but neither seems to be working. The created pods keep responding with a `CrashLoopBackOff`.
I don't know if there was anything else I had to do beforehand, because I only directly followed the procedure as shown on the documentation.
![image](https://user-images.githubusercontent.com/34566758/114324100-a722b980-9b28-11eb-8dca-6752a2efdfba.png)

**Kong Ingress controller version**
Attempt for 1.2.X

### Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-31T15:47:28Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/arm64"}
```

### Environment
- **OS**: Ubuntu 20.04.2 LTS
- **Kernel**: Linux ubuntu 5.4.0-1032-raspi

### Expected behavior
External IP gets assigned and no kong pods should fail.

**Comment by tobiolalusi** [comment] 2021-04-12 13:04
I decided to try install KIC on my personal laptop itself, instead of my Raspberry Pi as I was previously doing, and it works as expected. Looks like the problem has something to do with the computer's architecture.

**Comment by shaneutt** [comment] 2021-04-12 13:05
Hi @tobiolalusi :wave: 

Assuming I understood you correctly you're running on an ARM64 machine. The Kong Kubernetes Ingress Controller currently only officially supports the x86_64 platform at this time, however there is work underway to evaluate and ultimately see if we want to support ARM64 (and other platforms) officially:

* https://github.com/Kong/kubernetes-ingress-controller/issues/451
* https://github.com/Kong/kubernetes-ingress-controller/pull/926

I would recommend subscribing to these issues and adding your input there promoting your use case, as the decisions around whether to support ARM64 are still underway.

I'm going to close this as a duplicate of #451, but if you feel there's still reasons this doesn't fit cleanly into that work, please feel free to re-open and ping me :bow:

**Closed by shaneutt** 2021-04-12 13:05 UTC
Labels: area/multi-arch
