### ISSUE TITLE
Flaky test `TestNodeAgentUpdateNodes/update_status_existing_kic_node`

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#3790] opened 2023-03-22 11:05 UTC
It seems that the test doesn't wait a long enough wait time, currently set to 2 seconds.

https://github.com/Kong/kubernetes-ingress-controller/blob/a932fc9fa9d8eaa44a6e610e48a8ab8e98fa2e42/internal/konnect/node_agent_test.go#L464-L465

Failed CI run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4488836821/jobs/7893931750

```
=== RUN   TestNodeAgentUpdateNodes/update_status_existing_kic_node
    node_agent.go:88: konnect-node: "level"=0 "msg"="Starting Konnect NodeAgent" "runtime_group_id"="cluster-00"
?   	github.com/kong/kubernetes-ingress-controller/v2/internal/konnect/runtimegroupsconfig	[no test files]
    node_agent_test.go:434: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/konnect/node_agent_test.go:434
        	Error:      	Condition never satisfied
        	Test:       	TestNodeAgentUpdateNodes/update_status_existing_kic_node
--- FAIL: TestNodeAgentUpdateNodes/update_status_existing_kic_node (2.00s)
```

**Comment by rainest** [comment] 2023-09-13 22:10
There was a duplicate of this issue. It has been addressed: https://github.com/Kong/kubernetes-ingress-controller/pull/3974

**Closed by rainest** 2023-09-13 22:10 UTC
Labels: area/tests, test-flake
