### ISSUE TITLE
Ingress Controller CrashBackLoop -After adding incorrect Basic Auth Secret 

### ISSUE THREAD

**Issue by satwant17** [Kong/kubernetes-ingress-controller#553] opened 2020-02-26 16:47 UTC
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.
---

### Summary
Running KONG Ingress Controller in GKE. Configuring as service with basic-auth. When trying to setup consumer credentials i configured basic-auth secret incorrectly due to which ingresscontroller controller was in crashback loop

**Kong Ingress controller version**
KIC 0.7.1

**Kong or Kong Enterprise version**
1.3.0.2-alpine

### Kubernetes version

**paste `kubectl version` output**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
### Environment
GKE

### What happened
Created incorrect secret for basic auth and configured that for a consumer which made ingress controller container crash

Basic auth secret (Incorrect)  
kubectl create secret generic my-basicauth  \
  --from-literal=kongCredType=basic-auth  \
  --from-literal=key=myuser  \

it should have been 
kubectl create secret generic my-basicauth  \
  --from-literal=kongCredType=basic-auth  \
  --from-literal=username=myuser  \
  --from-literal=password=mypassword

### Expected behavior

Maybe just show show error and not crash the ingresses container
### Steps To Reproduce

1.Configure a service with basic auth 
2.Create a consumer 
3.Create INCORRECT credentials
4.Attach the incorrect credentials to the consumer

NOTE: Quick fix was to delete the old "Incorrect" secret and create a valid  secret

**Comment by guneemwelloeux** [comment] 2020-04-23 11:57
I encountered this exact same issue on my side as well, and should probably be addressed.

**Comment by guneemwelloeux** [comment] 2020-04-23 11:59
Duplicate of https://github.com/Kong/kubernetes-ingress-controller/issues/532

**Closed** 2020-04-28 22:57 UTC
