### ISSUE TITLE
deploy: add example daemon set deployment

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#682] opened 2020-05-21 22:51 UTC
Users have requested for DaemonSet based deployments of Kong Ingress Controller.

**Comment by Arjunkrisha** [comment] 2021-01-25 10:16
Even in our case we would like to have a daemonset based deployment.
Usecase: We have k8s cluster with 3 nodes deployed over openstack. Currently our environment does not support Loadbalancer type services. We can go for nodeport/hostnetwork, but that means we need to ensure that the services are deployed on all the nodes. We have a LB at the front that does a TCP forwarding to these hosts. Hence if the pod is present on each nodes, then we can make this work.

We did a similar approach for nginx ingress and it worked fine. Hoping to have the same for kong soon.

**Comment by hbagdi** [comment] 2021-01-25 16:12
@Arjunkrisha Would you be open to contributing one?
It is not terribly complicated to take the existing Deployment manfiest and make a DaemonSet out of it.

**Comment by shaneutt** [comment] 2021-01-25 17:09
@Arjunkrisha I would recommend subscribing to https://github.com/Kong/kubernetes-ingress-controller/issues/702 as this work will structurally change the way the controller and proxies are deployed _in such a way that I expect will make implementing the proxy daemonset option you're requesting here simpler_.

In the meantime while waiting for the daemonset option I wanted to suggest a 3rd party open source tool which may be able to help you get some of the behavior you want, called [MetalLB](https://github.com/metallb/metallb). I noticed you mentioned your current environment "does not support LoadBalancer type services", and MetalLB is a tool which can enable `LoadBalancer` type `Services` for you in on-prem and air-gapped environments, or otherwise in environments where cloud or other application load balancers implementations are not available to your cluster. If this sounds like something that might help you MetalLB has [documentation site](https://metallb.universe.tf/) and a [community mailing list](https://groups.google.com/g/metallb-users) where you can get help setting it up in your environment.

**Comment by Arjunkrisha** [comment] 2021-01-27 09:07
> @Arjunkrisha Would you be open to contributing one?
> It is not terribly complicated to take the existing Deployment manfiest and make a DaemonSet out of it.

Sure will try that :)

**Comment by Arjunkrisha** [comment] 2021-01-27 09:14
Thanks @shaneutt for the suggestion.
our k8s team is having that as an option as well. But for now to get this API gateway going we need to do it without the metallb or loadbalancer option. 

Planning to modify the helm chart locally and test for daemonsets. Let me know if i need to keep anything in mind while doing this, so that i can get it working as a daemonset

**Comment by Arjunkrisha** [comment] 2021-01-29 07:06
Hey Guys. I made the changes locally. But confused on how to create a pull request after seeing the https://github.com/Kong/charts/blob/main/CONTRIBUTING.md.

I made changes in my local branch `latest`. I did a `git rebase next`. How to create a pull request now ?

**Comment by arjunkrishnasb** [comment] 2021-02-01 05:56
For some reason i could not push my branch. Any thoughts ?


(base) ARJSRIRA-M-L0XP:charts arjsrira$ git push --set-upstream origin latest
Username for 'https://github.com': arjunkrishnasb
Password for 'https://arjunkrishnasb@github.com': 
remote: Permission to Kong/charts.git denied to arjunkrishnasb.
fatal: unable to access 'https://github.com/Kong/charts.git/': The requested URL returned error: 403
(base) ARJSRIRA-M-L0XP:charts arjsrira$

**Comment by arjunkrishnasb** [comment] 2021-02-01 06:00
Hey guys, let me know if you guys know what the issue is. I would love to contribute more. Though this is a minor feature addition in deployment i think this would help many :)

**Comment by shaneutt** [comment] 2021-02-01 13:20
Hey @arjunkrishnasb have you tried setting your fork of the repo as the upstream (instead of this repo)? You can then start a PR (or draft PR if you prefer) from your fork and we can help review and provide help.

**Comment by arjunkrishnasb** [comment] 2021-02-02 06:17
I guess you mean fork the repo and create a PR in it and then you can update in the main repo ?
Will do that today and if anything else let me know

**Comment by arjunkrishnasb** [comment] 2021-02-02 06:50
Kindly have a look and approve if this looks good https://github.com/Kong/charts/pull/269

**Comment by arjunkrishnasb** [comment] 2021-02-02 07:03
I tried to agree the contributer license , but it gave an internal server error

**Comment by shaneutt** [comment] 2021-02-03 13:10
It looks like the CLA issue may be coming from the submission author info:
```
arjsrira seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.
You have signed the CLA already but the status is still pending? Let us recheck it.
```
Perhaps there's some issue with the email address used for the commits vs. what's being used to sign the CLA?

**Comment by arjunkrishnasb** [comment] 2021-02-08 10:26
Thanks @shaneutt 
All tests passed. Just need to review

**Comment by debu99** [comment] 2021-03-05 07:29
when this can be merged?

**Comment by tuananh2508** [comment] 2021-08-18 10:45
Just wonder when will we have this feature ?

**Comment by shaneutt** [comment] 2021-08-18 14:09
There is now daemonset support in the chart as of https://github.com/Kong/charts/pull/347 which was the follow up to https://github.com/Kong/charts/pull/269. Let us know if there's anything further you wish to see in this regard.

**Closed by shaneutt** 2021-08-18 14:09 UTC
Labels: severity/low
