### ISSUE TITLE
Unexpected failure updating Kong configuration

### ISSUE THREAD

**Issue by Djiit** [Kong/kubernetes-ingress-controller#746] opened 2020-06-24 13:01 UTC
### Summary

Kong isn't working since a restart. I can see strange errors in the logs.

**Kong Ingress controller version**

0.7.1

**Kong or Kong Enterprise version**

1.5

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: AWS EKS

### What happened

Kong got Evicted for Memory Usage. Now, when starting, it doesn't pick its own configuration and I can see this error spamming the logs :

```
E0624 13:00:08.401512       1 controller.go:119] unexpected failure updating Kong configuration:
posting new config to /config: 500 Internal Server Error <html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
</body>
</html>
W0624 13:00:08.401543       1 queue.go:112] requeuing assets-paris-dev/sh.helm.release.v1.api-certificate-generator.v3, err posting new config to /config: 500 Internal Server Error <html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
</body>
</html>
```

Things to note  : I don't know why Kong is trying to requeue this secrets (the sh.helm one).

### Expected behavior

Kong restarts and things go on normally.

### Steps To Reproduce

No idea, sorry. It just happened and now Kong is unusable.

**Comment by Djiit** [comment] 2020-06-24 13:14
I can see another error from time to time : 
```
│ proxy 2020/06/24 13:13:45 [error] 30#0: *15168 [kong] api_helpers.lua:260 Cannot serialise table: excessively sparse array, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "localhost:8444"   │
```

**Comment by hbagdi** [comment] 2020-06-24 16:56
You are running into https://github.com/Kong/kong/issues/5768, the fix is merged in but not yet released.
Can you use kong 2.1.0-beta1 image for this?

**Comment by Djiit** [comment] 2020-06-25 06:54
I think I can, yes. I'll try to find a moment to test it out and will keep you posted here.

**Comment by atikhono** [comment] 2020-07-10 09:04
I'm seeing something similar (well in a way) with 2.1.0-beta1 and KIC 0.9.1. Running in AKS 1.15.11, 3 pods, db-less. No error from Kong/kong#5768 in Kong logs.

```
E0710 05:46:01.012093       1 controller.go:128] unexpected failure updating Kong configuration: 
posting new config to /config: 500 Internal Server Error {"message":"An unexpected error occurred"}
W0710 05:46:01.012139       1 queue.go:112] requeuing default/increased-timeout, err posting new config to /config: 500 Internal Server Error {"message":"An unexpected error occurred"}
```

The error is rare, occurring randomly in time and not simultaneous in all kong pods. If I restart pod, it syncs configuration without errors. Our monitoring system reported invalid SSL certificate issue once, around the time this happened:

```
W0710 05:46:30.963562       1 queue.go:112] requeuing default/increased-timeout, err posting new config to /config: 500 Internal Server Error {"message":"An unexpected error occurred"}
I0710 05:46:34.030230       1 kong.go:68] no configuration change, skipping sync to Kong
I0710 05:55:54.498295       1 kong.go:81] successfully synced configuration to Kong
```

(We upgraded to 2.1.0-beta1 to resolve the TLS breakage actually, because 2.0.5 was not released at the time we hit the bug heavily)

Also in ingress controller logs I see this sometimes (looks unrelated but who knows):

```
E0709 23:35:51.764732       1 reflector.go:307] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to watch *v1.Service: Get "https://10.0.0.1:443/api/v1/services?allowWatchBookmarks=true&resourceVersion=69347513&timeout=8m58s&timeoutSeconds=538&watch=true": dial tcp 10.0.0.1:443: connect: connection refused
...
W0709 23:35:52.869074       1 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: watch of *v1.Service ended with: too old resource version: 69347513 (69369016)
```

**Comment by hbagdi** [comment] 2020-07-13 17:21
> I'm seeing something similar (well in a way) with 2.1.0-beta1 and KIC 0.9.1. Running in AKS 1.15.11, 3 pods, db-less. No error from Kong/kong#5768 in Kong logs.

Can you share the logs of the kong container from around the same time when the controller container logs the `unexpected failure updating Kong configuration` error? That would help us figure out the root cause of why this is happening.

cc @Kong/team-core

**Comment by hbagdi** [comment] 2020-09-11 21:22
Closing this due to lack of activity. Please re-open if needed.

**Closed by hbagdi** 2020-09-11 21:22 UTC
