### ISSUE TITLE
KONG_KIC added to the flat manifests and Kustomize, and verified in the chart

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2078] opened 2021-12-09 21:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

`KONG_KIC=true` is not in the Kong container environment variables in https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-dbless.yaml and friends. We want it to be there.

### Proposed Solution

Add it: https://github.com/Kong/kubernetes-ingress-controller/blob/6040356d826aed9fc6a64686b9d96c5b899c23b8/config/base/kong-ingress-dbless.yaml#L26-L50

### Acceptance Criteria

- [x] Generated all-in-one manifests include `KONG_KIC=true` in the Kong container environment variables.
- [x] Helm chart always adds `KONG_KIC` when KIC is running (this is likely the case already - just pending verification to be sure)
- [x] Kustomize manifests always add `KONG_KIC`

**Comment by mflendrich** [comment] 2021-12-15 15:55
duplicate of #2074. Closing that one and copying the ACs from there over to this one.

**Comment by rainest** [comment] 2021-12-15 19:19
For reference, in the chart:

https://github.com/Kong/charts/blob/cb1d9388dee0ab58ea501934b66db003e2c2768d/charts/kong/templates/_helpers.tpl#L646-L648

**Closed** 2021-12-15 21:28 UTC
