### ISSUE TITLE
Rewrite `Status` handling

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2007] opened 2021-11-10 18:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

- #1492 
- Gateway controller watches the publish service, while the existing "legacy" `Status` reconciler reads the publish service on startup only. We need to unify these mechanisms.

### Proposed Solution

TBD

### Additional information

@shaneutt proposed a solution (potentially not feasible - not verified) that we shall drop the thread that updates statuses in favor of controllers updating object statuses directly.

### Acceptance Criteria

AC for the spike:
- [ ] KEP defines the scenarios in which status updates and/or events will be published (e.g. backpropagated `deck sync` errors, possibly validation errors caught post-apply, etc.)
- [ ] KEP an/or issues with a proposed solution to the race condition problem and to unification of how KIC reads the publish service.
- [ ] New system still reflects the status of configuration actually applied in Kong: configuration for a given Ingress must have successfully applied before we populate its status information.

**Comment by shaneutt** [comment] 2022-01-24 18:12
I have marked this `severity/high` because we keep having issues pop up in the existing system.

**Comment by shaneutt** [comment] 2022-02-24 20:50
closing as a duplicate of https://github.com/Kong/kubernetes-ingress-controller/issues/1492, which is now marked `severity/high` as well.

**Closed by shaneutt** 2022-02-24 20:50 UTC
Labels: area/spike, severity/high
