### ISSUE TITLE
KIC 2.0 - Ingress LoadBalancer Status Parity

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1350] opened 2021-05-25 17:32 UTC
The `Ingress` controllers for `extensions.v1beta1`, `net.v1beta1` and `net.v1` need to add missing `.status.loadBalancer` updates for parity with how these statuses are handled in 1.x.

Acceptance Criteria:
- [ ] all 3 supported `Ingress` APIs get `status` updates that matches what we do for KIC 1.x
- [ ] integration tests are added that prove the status updates and protect against regressions to them

**Comment by mflendrich** [comment] 2021-06-29 14:22
duplicate of #1349

**Closed by mflendrich** 2021-06-29 14:22 UTC
Labels: area/cleanup, priority/medium, size/medium
