### ISSUE TITLE
KIC did not release memory in a timely manner when DP was downsized

### ISSUE THREAD

**Issue by tao12345666333** [Kong/kubernetes-ingress-controller#6235] opened 2024-06-24 12:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I deployed KIC in a new cluster and created an Ingress resource. 

When I scaled up the gateway (from 1 to 30) and then scaled it down (from 30 to 1), I found that the memory of KIC was not released promptly.

### Expected Behavior

When the number of DP decreases, KIC can correctly release memory.

### Steps To Reproduce

```markdown
1. Install KIC and create an Ingress resource, via https://docs.konghq.com/kubernetes-ingress-controller/latest/get-started/
2. `kubectl top` check the memory of KIC's pod
3. `kubectl scale deployment/kong-gateway -n kong --replicas 30`
4. check the memory again
5. `kubectl scale deployment/kong-gateway -n kong --replicas 1`
6. check the memory again
```

### Kong Ingress Controller version

```shell
3.2
```

### Kubernetes version

```shell
v1.29
```

### Anything else?

Related to FTI-5975

**Comment by czeslavo** [comment] 2024-06-25 09:39
https://github.com/Kong/kubernetes-ingress-controller/issues/5068 can be related to this.

**Comment by tao12345666333** [comment] 2024-07-22 15:57
Yes, I am fixing #5068, for more details please refer to  https://github.com/Kong/kubernetes-ingress-controller/issues/5068#issuecomment-2232675192

**Comment by tao12345666333** [comment] 2024-07-30 06:27
When I tested the code containing modifications related to #5068, I found that there was not much fluctuation in KIC's memory.

![image](https://github.com/user-attachments/assets/8fc2732c-d8ae-45aa-840d-e1d6090c6f9c)

In this test, I ran two replicas of KIC and installed them using Helm. I performed a scale operation on the Gateway, changing the number of replicas from 1 to 20, and then reduced it back to 1 after running for some time.

**Comment by czeslavo** [comment] 2024-07-30 15:00
@tao12345666333 Are you still able to reproduce the issue with KIC 3.2 without modifications? I tried reproducing leaks (or https://github.com/Kong/kubernetes-ingress-controller/issues/5068's ready list being stuck) but didn't succeed.

**Comment by tao12345666333** [comment] 2024-07-30 15:08
Let me try the v3.2 version.

**Comment by tao12345666333** [comment] 2024-07-31 09:26
update: The latest code and v3.2 were unable to reproduce the issue.

I will try KIC + Konnect to reproduce this issue.

**Comment by randmonkey** [comment] 2024-08-12 10:15
@tao12345666333 Could not reproduce in the latest code, close this.

**Closed by randmonkey** 2024-08-12 10:15 UTC
Labels: bug
