### ISSUE TITLE
Drop extensions/v1beta1 wire protocol

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1478] opened 2021-07-01 18:28 UTC
KIC currently can talk `extensions/v1beta1` Ingress with the API server, alongside `networking.k8s.io/v1beta1` and `networking.k8s.io/v1`.

Given the other planned efforts:
- #763 will drop support for <1.16
- the easiest way to do #801 is by upgrading the CRD apiversions to v1, which means dropping support for <1.16

it makes sense to remove support for `extensions/v1beta1` (which will make KIC incompatible with <1.14) in the near future because these other efforts will likely mean an even stronger bump in the minimal k8s version supported.

This is unrelated to the API versions of resources that the user puts in the cluster. So dropping extensions/v1beta1 in KIC will not mean that the user will not be able to use that API version with KIC (because the API server will do the not-so-heavy-lifting to convert it to a newer version) - it only means that we will drop support for Kubernetes versions that cannot talk anything newer than extensions.v1beta1 (meaning older than 1.14).

**Comment by shaneutt** [comment] 2022-03-22 20:17
closing as a duplicate of https://github.com/Kong/kubernetes-ingress-controller/issues/1666

**Closed by shaneutt** 2022-03-22 20:17 UTC
Labels: severity/low, onboarding, area/maintenance, nice-to-have
