### ISSUE TITLE
Flaky conformance tests

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#2939] opened 2022-09-15 09:22 UTC
Looks like a timeout waiting on some condition:

```
    --- FAIL: TestGatewayConformance/Multiple_HTTP_listeners_with_the_same_port_and_different_hostnames,_each_with_a_different_HTTPRoute (61.14s)
```

Related CI run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3059105976/jobs/4936093386#step:5:10547

Test's source code: https://github.com/kubernetes-sigs/gateway-api/blob/v0.5.0/conformance/tests/httproute-listener-hostname-matching.go

More examples (from #2931):
* `HTTPRoutes_should_attach_to_listeners_only_if_they_have_intersecting_hostnames,_and_should_accept_requests_only_for_the_intersecting_hostnames/HTTPRoutes_that_do_intersect_with_listener_hostnames`. Example [here](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3264291479/jobs/5364700723).
* `TestGatewayConformance/Multiple_HTTP_listeners_with_the_same_port_and_different_hostnames,_each_with_a_different_HTTPRoute`. Example [here](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3278379841/jobs/5396702530).

### Expected Behavior

Conformance tests shouldn't be flaky.

### Acceptance Criteria

- [ ] The test `HTTPRoutes_should_attach_to_listeners_only_if_they_have_intersecting_hostnames,_and_should_accept_requests_only_for_the_intersecting_hostnames/HTTPRoutes_that_do_intersect_with_listener_hostnames` is not flaky anymore.
- [ ] The test `TestGatewayConformance/Multiple_HTTP_listeners_with_the_same_port_and_different_hostnames,_each_with_a_different_HTTPRoute` is not flaky anymore.

**Comment by pmalek** [comment] 2022-09-28 14:27
Happened again here: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3144265424/jobs/5110042446#step:5:10559

**Comment by pmalek** [comment] 2022-09-29 12:56
Again here: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3151366008/jobs/5125225723

**Comment by pmalek** [comment] 2022-09-29 14:46
It seems that even in isolation the test mentioned in the issue fails (not consistently)

```
--- FAIL: TestGatewayConformance (73.19s)
    --- FAIL: TestGatewayConformance/Multiple_HTTP_listeners_with_the_same_port_and_different_hostnames,_each_with_a_different_HTTPRoute (61.33s)
        --- FAIL: TestGatewayConformance/Multiple_HTTP_listeners_with_the_same_port_and_different_hostnames,_each_with_a_different_HTTPRoute/0_request_to_bar.com/_should_go_to_infra-backend-v1 (30.00s)
        --- PASS: TestGatewayConformance/Multiple_HTTP_listeners_with_the_same_port_and_different_hostnames,_each_with_a_different_HTTPRoute/1_request_to_foo.bar.com/_should_go_to_infra-backend-v2 (26.11s)
        --- PASS: TestGatewayConformance/Multiple_HTTP_listeners_with_the_same_port_and_different_hostnames,_each_with_a_different_HTTPRoute/2_request_to_baz.bar.com/_should_go_to_infra-backend-v3 (0.04s)
```

I've also observed other tests failing (not consistently)

```
    --- FAIL: TestGatewayConformance/A_single_HTTPRoute_in_the_gateway-conformance-infra_namespace_should_fail_to_attach_to_a_Gateway_in_the_same_namespace_if_the_route_has_a_backendRef_Service_in_the_gateway-conformance-app-backend_namespace_and_a_ReferenceGrant_exists_but_does_not_grant_permission_to_route_to_that_specific_Service (58.28s)
        --- PASS: TestGatewayConformance/A_single_HTTPRoute_in_the_gateway-conformance-infra_namespace_should_fail_to_attach_to_a_Gateway_in_the_same_namespace_if_the_route_has_a_backendRef_Service_in_the_gateway-conformance-app-backend_namespace_and_a_ReferenceGrant_exists_but_does_not_grant_permission_to_route_to_that_specific_Service/HTTPRoute_with_BackendRef_in_another_namespace_and_no_ReferenceGrant_covering_the_Service_has_a_ResolvedRefs_Condition_with_status_False_and_Reason_RefNotPermitted (0.00s)
        --- FAIL: TestGatewayConformance/A_single_HTTPRoute_in_the_gateway-conformance-infra_namespace_should_fail_to_attach_to_a_Gateway_in_the_same_namespace_if_the_route_has_a_backendRef_Service_in_the_gateway-conformance-app-backend_namespace_and_a_ReferenceGrant_exists_but_does_not_grant_permission_to_route_to_that_specific_Service/HTTP_Request_to_invalid_backend_with_missing_referenceGrant_should_receive_a_500 (30.00s)
        --- PASS: TestGatewayConformance/A_single_HTTPRoute_in_the_gateway-conformance-infra_namespace_should_fail_to_attach_to_a_Gateway_in_the_same_namespace_if_the_route_has_a_backendRef_Service_in_the_gateway-conformance-app-backend_namespace_and_a_ReferenceGrant_exists_but_does_not_grant_permission_to_route_to_that_specific_Service/HTTP_Request_to_valid_sibling_backend_should_succeed (22.11s)
```

Those all look like they hit a timeout set by default in the gateway-api repo: https://github.com/kubernetes-sigs/gateway-api/blob/35ad4f43bfee1362bdcff79d8db2e5b1f8342b82/conformance/utils/http/http.go#L66
What's interesting is that this was made configurable just recently (after v0.5.1) https://github.com/kubernetes-sigs/gateway-api/blob/7c52e02fd3845048184ff6e0125000b7f50ccf8d/conformance/utils/config/timeout.go#L75-L135

While the underlying problem (whatever it is) is not found yet bumping the timeout (when a version with those tunables is released : v0.6.0?) seems like a plausible idea to try to fix these failures

**Comment by pmalek** [comment] 2022-09-30 13:09
again, this time on `main`: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3158783630/jobs/5141208620#step:5:5932

**Comment by randmonkey** [comment] 2022-10-13 10:17
From recent failures of conformance tests, the errors happen here:
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3241073981/jobs/5313100563
```
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/conformance/helpers.go:278
        	            				/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/conformance/helpers.go:175
        	            				/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/conformance/httproute-simple-same-namespace.go:42
        	            				/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/conformance/suite.go:192
        	            				/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/conformance/gateway_conformance_test.go:95
```
It times out on waiting for `HTTPRoute`s to have a `Accepted` parent status in its conditions. Unfortunately, in v0.5.1 we still could not update the timeout. It may be fixed by setting `timeoutConfig.HTTPRouteMustHaveParents` after the change released in a new version. 
I would still mark this as blocked by this upstream change. Also, I would do some investigation on how to reduce the duration of getting marked parent Accepted.

**Comment by randmonkey** [comment] 2022-10-13 10:18
blocked by: release of https://github.com/kubernetes-sigs/gateway-api/blob/7c52e02fd3845048184ff6e0125000b7f50ccf8d/conformance/utils/config/timeout.go#L75-L135

**Comment by pmalek** [comment] 2022-10-13 10:21
Although increasing the timeout might help I'm not convinced that it will. In cases where the test passes it happens rather quickly, while in those where it fails it times out (as mentioned above).

I'm more inclined into believing that it is related to controller being stuck for some reason but I might be proven wrong.

**Comment by jrsmroz** [comment] 2022-11-01 01:06
It seems the problem is that when HTTPRoute is attached to the gateway, the `ListenerStatus.AttachedRoutes` is not updated.  We never update the `AttachedRoutes`, it's always zero: 
- https://github.com/Kong/kubernetes-ingress-controller/blob/main/internal/controllers/gateway/gateway_utils.go#L210-L234
- https://github.com/Kong/kubernetes-ingress-controller/blob/main/internal/controllers/gateway/gateway_utils.go#L291

Grepping code show there are no other places where we set `AttachedRoutes`

**Closed** 2023-02-02 19:35 UTC
Labels: area/tests, test-flake
