### ISSUE TITLE
Run upgrade tests 

### ISSUE THREAD

**Issue by ccfishk** [Kong/kubernetes-ingress-controller#1656] opened 2021-08-04 16:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We have breaking changes in 2.0, user would have broken controller after upgrade.

### Proposed Solution

We need ensure there is no regression when user upgrade from 1.3 to 2.0
Run upgrade tests against beta
Run upgrade tests against Kong Enterprise

**Comment by shaneutt** [comment] 2021-08-04 17:03
We do basic upgrade tests from v1 to v2 in the https://github.com/kong/charts repository on each PR right now, just a heads up.

**Comment by rainest** [comment] 2021-08-11 16:52
I ran through https://gist.github.com/rainest/cf4db9b0e607f0e719470166f3cf2634 (install all the 1.3 flat manifests, confirm some basic Ingress handling, install the equivalent 2.0.0-alpha.3 manifest over top, confirm updated Pods come online and that the Ingress still routes) successfully earlier. The caveats then were:

1. 2.x deployment files weren't updated to reflect the latest image available. We need to remember to do that during a release.
1. The alpha.3 images still fail because we accidentally restored a bug that requires Knative CRDs to start unless you explicitly disable that controller. https://github.com/Kong/kubernetes-ingress-controller/pull/1585 should resolve that.
1. The RBAC role names and bindings do differ between 1.x and 2.x. This does not cause any direct issue, since that role is what the 2.x Deployments reference. It will leave the now-unused 1.x role and binding around. They should be deleted for cleanliness, but are benign.

All but the third of those has been addressed in the beta, and the third we can't really address beyond documentation (you just have to manually delete the old SA and binding). Is there anything further we wanted to test?

**Comment by ccfishk** [comment] 2021-08-17 16:44
Image kong/kubernetes-ingress-controller:2.0.0-beta.2 should have resolved issue 1 &2.

Interms of of 3, I would propose a prepare/cleanup function within 2.x controller, which basically remove all non-used (1.x) RBAC role names and bindings before KIC ready for work. Or put it another word, only keep 2.x required RBAC role in the cluster.

**Comment by mflendrich** [comment] 2021-08-31 17:09
https://github.com/Kong/charts/issues/450 is a known upgrade regression in KIC 2.0.

**Closed** 2021-08-31 17:16 UTC
