### ISSUE TITLE
Kong deployment failing from kustomize

### ISSUE THREAD

**Issue by Reefay** [Kong/kubernetes-ingress-controller#601] opened 2020-04-15 14:56 UTC
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---
I'm deploying using the kustomize instructions from https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/deployment/k4k8s.md#kustomize.

Kustomize runs and deploys all the things. The pod is in a state of 1/2 and Error. I describe on the pod i get these errors:

- Liveness probe failed: Get http://<pod ip>:10254/healthz: dial tcp 10.200.17.171:10254: connect: connection refused
- Readiness probe failed: Get http://<pod ip>:10254/healthz: dial tcp 10.200.17.171:10254: connect: connection refused 

I've tried opening the 10254 port on the ingress-controller and proxy containers, but still doesn't work. I've tried commenting out the liveness and readiness probes, but still fails. 

This is a generic installation from your github. I would expect it to work out of the box with no modifications. I need some help.

### Summary

Default Kong installation from Kustomize fails installation

0.8.0

Kong

v1.15.5

### Environment

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**: Kustomize, Kubectl
- **Others**:

### What happened
Using the default kustomize Kong deployment, liveness and readiness probes fail in ingress-controller. Commenting out these probes, pod still fails.

### Expected behavior
Kong deploys and is ready for configuration/use

### Steps To Reproduce

1. kustomize build github.com/kong/kubernetes-ingress-controller/deploy/manifests/base > deployment.yaml
2. kubectl apply -f deployment.yaml
3. kubectl get pods -nkong -w
4. Watch ingress-kong pod go from 1/2 to restarting to error to CrashLoopBackOff
5. See logs below
6. kubectl describe pod <pod> -nkong
7. See Container ingress-controller failed liveness probe, will be restarted

Logs:
Proxy
2020/04/15 14:48:20 [notice] 1#0: using the "epoll" event method
2020/04/15 14:48:20 [notice] 1#0: openresty/1.15.8.3
2020/04/15 14:48:20 [notice] 1#0: built by gcc 9.2.0 (Alpine 9.2.0)
2020/04/15 14:48:20 [notice] 1#0: OS: Linux 4.15.0-70-generic
2020/04/15 14:48:20 [notice] 1#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2020/04/15 14:48:20 [notice] 1#0: start worker processes
2020/04/15 14:48:20 [notice] 1#0: start worker process 22

ingress-controller:
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    0.8.0
  Build:      4b80e3f
  Repository: git@github.com:kong/kubernetes-ingress-controller.git
  Go:         go1.14.1
-------------------------------------------------------------------------------

W0415 15:00:19.895330       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0415 15:00:19.896162       1 main.go:442] Creating API client for https://10.100.200.1:443
I0415 15:00:19.903133       1 main.go:486] Running in Kubernetes Cluster version v1.15 (v1.15.5) - git (clean) commit 20c265fef0741dd71a66480e35bd69f18351daea - platform linux/amd64
F0415 15:00:49.905702       1 main.go:185] making HTTP request: Get "https://localhost:8444/": dial tcp 10.0.120.79:8444: i/o timeout

**Comment by hbagdi** [comment] 2020-04-15 20:50
I can't reproduce this.
Can you share your `deployment.yaml` file that is generated via kustomize?

**Comment by Reefay** [comment] 2020-04-15 21:05
We also cloned your repo and used the manifest/base and had the same error.
[deployment.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4483729/deployment.txt)

**Comment by hbagdi** [comment] 2020-04-15 21:09
> If we have a current NGINX deployment in this cluster in a different namespace, it shouldn't affect this deployment, correct? We're trying to deploy this in parallel to not affect connections.

Correct.

The deployment looks correct.
Can you share the output of `kubectl describe pods -n kong` and also share the logs of the kong container?

**Comment by Reefay** [comment] 2020-04-15 21:28
[kong-pod-describe.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4483799/kong-pod-describe.txt)
[kong-pod-proxy.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4483800/kong-pod-proxy.txt)
[kong-pod-ingress-controller.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4483801/kong-pod-ingress-controller.txt)

**Comment by hbagdi** [comment] 2020-04-15 23:07
I don't see anything off in those. The only note I can make is that it is a `gov` region of AWS it seems.
@rainest Any clue on what's going on here?

**Comment by Reefay** [comment] 2020-04-16 00:09
It is in the us govcloud. I was able to have the service create an ELB. I wouldn't think bring in govcloud would make a difference.

**Comment by rainest** [comment] 2020-04-16 01:33
None from the information presented. Do you see anything of interest if you add `KONG_LOG_LEVEL=debug` to the Kong container environment?

@hbagdi I know less on the cluster networking end, but what would cause a TCP timeout? Normally I'd expect a RST if listens are misconfigured or failed to bind. Is there some way that connection request would get filtered or misrouted within a pod?

**Comment by Reefay** [comment] 2020-04-16 01:54
[kong-pod-proxy.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4484477/kong-pod-proxy.txt)
The proxy had updated logs with debug. The ingress-controller did not.
One thing I thought was weird, is that the healthz is on port 10254, yet I didn't see the container opening that port. I did try to open it, but it still failed.

**Comment by hbagdi** [comment] 2020-04-16 21:58
> The ingress-controller did not.

Can you add a cli arg to the ingress controller container: `-v 10`?


Let's check another thing: `kubectl apply -f https://bit.ly/k4k8s`, does that result in any errors?

Also, do you have any network policies installed? Although, that can't explain why health-checks would fail.

**Comment by rainest** [comment] 2020-04-16 22:37
Are you able to connect to it if you forward into the pod?

```
kubectl port-forward -n kong POD_NAME 8444:8444
curl -ksv https://localhost:8444
```

**Comment by Reefay** [comment] 2020-04-17 04:23
Hi. I ran through all your steps. Here's the log output. The k4k8s still failed in the same way.

[kong-pod-describe-k4k8s.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4490879/kong-pod-describe-k4k8s.txt)
[kong-pod-proxy-k4k8s.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4490881/kong-pod-proxy-k4k8s.txt)
[kong-pod-ingress-controller-k4k8s.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4490882/kong-pod-ingress-controller-k4k8s.txt)
[curl-kong.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4490883/curl-kong.txt)
[kong-pod-describe.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4490884/kong-pod-describe.txt)
[kong-pod-proxy.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4490885/kong-pod-proxy.txt)
[kong-pod-ingress-controller.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4490886/kong-pod-ingress-controller.txt)

**Comment by rainest** [comment] 2020-04-17 17:47
It's attempting to talk to 8001, whereas the admin API is actually listening on 8444.
In the controller container describe info:
```
    Args:
      --v=10
      --publish-service=kong/kong-proxy
```
And in its startup logs (apparently printing a default):
```
I0417 04:16:33.586267       1 flags.go:227] FLAG: --kong-admin-url="http://localhost:8001"
```
In the earlier deployment.txt, it's trying to set the correct URL, but using the old arg name:
```
      - args:
        - /kong-ingress-controller
        - --kong-url=https://localhost:8444
```

**Comment by Reefay** [comment] 2020-04-17 18:12
I had to add that publish-service when you had me add the -v. When it was just the -v, the pod was failing out-right and was stating that it had to have --publish-service. I just copied what was up at the proxy. I don't know if this was correct.

**Comment by rainest** [comment] 2020-04-17 18:16
Originally thought #608 would address, but now not sure. @Reefay you can try with

```
kustomize build github.com/kong/kubernetes-ingress-controller/deploy/manifests/base?ref=17c045829b80ed25e5ff5500839934c95642dc91
```
However it looks like none of the args are actually making their way into the controller. These should both be set according to the deployment:

```
I0417 04:16:33.586188       1 flags.go:227] FLAG: --kong-url=""
I0417 04:16:33.586289       1 flags.go:227] FLAG: --kong-admin-tls-skip-verify=%!q(bool=false)
```
Another option is to try moving these to env instead, i.e. `CONTROLLER_KONG_ADMIN_URL: https://localhost:8444` and `CONTROLLER_KONG_ADMIN_TLS_SKIP_VERIFY: true`. I can't think of any obvious reason why those would not be applied, whereas the `--v=10` would be.

**Comment by Reefay** [comment] 2020-04-20 20:35
I tried adding in those env values. Still fails in the same manner. Thanks for the help but I'm going to have to move on to a different solution. Good luck guys.

**Comment by rlpatrao** [comment] 2020-04-24 02:10
Having the same issue via `kubectl apply -f https://bit.ly/kong-ingress-dbless`

here is the describe output on the pod: 

`
Name:         ingress-kong-84647f7f8f-z4c62
Namespace:    kong
Priority:     0
Node:         ip-xx/xx
Start Time:   Fri, 24 Apr 2020 01:48:46 +0000
Labels:       app=ingress-kong
              pod-template-hash=84647f7f8f
Annotations:  kuma.io/gateway: enabled
              prometheus.io/port: 9542
              prometheus.io/scrape: true
              traffic.sidecar.istio.io/includeInboundPorts:
Status:       Running
IP:           10.244.4.13
IPs:
  IP:           10.244.4.13
Controlled By:  ReplicaSet/ingress-kong-84647f7f8f
Containers:
  proxy:
    Container ID:   docker://c4edea5779c5f2c0d13e5f59cdc7e8f28ee664ad6c4cb7b94f72c6a56a407184
    Image:          kong:2.0
    Image ID:       docker-pullable://kong@sha256:f7a2bb6ae3baf60e3ca0d6ba5f83ebe3caf64fe8b6aa8dd6a5d3df16a22775c2
    Ports:          8000/TCP, 8443/TCP, 9542/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Fri, 24 Apr 2020 01:48:47 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:30010/health delay=10s timeout=2s period=10s #success=1 #failure=5
    Readiness:      http-get http://:30010/health delay=15s timeout=3s period=10s #success=1 #failure=5
    Environment:
      KONG_DATABASE:                off
      KONG_NGINX_WORKER_PROCESSES:  1
      KONG_NGINX_HTTP_INCLUDE:      /kong/servers.conf
      KONG_ADMIN_ACCESS_LOG:        /dev/stdout
      KONG_ADMIN_ERROR_LOG:         /dev/stderr
      KONG_ADMIN_LISTEN:            127.0.0.1:8444 ssl
      KONG_PROXY_LISTEN:            0.0.0.0:8000, 0.0.0.0:8443 ssl http2
    Mounts:
      /kong from kong-server-blocks (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kong-serviceaccount-token-f684p (ro)
  ingress-controller:
    Container ID:  docker://b8309bf9fe47258a5dec6b52e7b3ac0d925d6a8866b2795e3647093124a91bfa
    Image:         kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.8.1
    Image ID:      docker-pullable://kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller@sha256:c7ccb6600d166a4986a30decf8a2db06161240b77e745de25ec8ce459a6570fa
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      /kong-ingress-controller
      --kong-admin-url=https://localhost:8444
      --admin-tls-skip-verify
      --publish-service=kong/kong-proxy
    State:          Running
      Started:      Fri, 24 Apr 2020 01:49:19 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 24 Apr 2020 01:48:47 +0000
      Finished:     Fri, 24 Apr 2020 01:49:17 +0000
    Ready:          False
    Restart Count:  1
    Liveness:       http-get http://:30012/healthz delay=5s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:30012/healthz delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAME:       ingress-kong-84647f7f8f-z4c62 (v1:metadata.name)
      POD_NAMESPACE:  kong (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kong-serviceaccount-token-f684p (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kong-server-blocks:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kong-server-blocks
    Optional:  false
  kong-serviceaccount-token-f684p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kong-servi
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age               From                      Message
  ----     ------     ----              ----                      -------
  Normal   Scheduled  <unknown>         default-scheduler         Successfully assigned kong/ingress-kong-84647f7f8f-z4c62 to ip-xx
  Normal   Pulled     38s               kubelet, ip-xx  Container image "kong:2.0" already present on machine
  Normal   Created    38s               kubelet, ip-xx  Created container proxy
  Normal   Started    38s               kubelet, ip-xx  Started container proxy
  Warning  Unhealthy  25s               kubelet, ip-xx  Liveness probe failed: Get http://10.244.4.13:30010/health: dial tcp 10.244.4.13:30010: connect: connection refused
  Warning  Unhealthy  9s (x3 over 29s)  kubelet, ip-xx  Readiness probe failed: Get http://10.244.4.13:30012/healthz: dial tcp 10.244.4.13:30012: connect: connection refused
  Normal   Pulled     7s (x2 over 38s)  kubelet, ip-xx  Container image "kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.8.1" already present on machine
  Normal   Created    7s (x2 over 38s)  kubelet, ip-xx  Created container ingress-controller
  Warning  Unhealthy  7s (x3 over 27s)  kubelet, ip-xx  Liveness probe failed: Get http://10.244.4.13:30012/healthz: dial tcp 10.244.4.13:30012: connect: connection refused
  Normal   Killing    7s                kubelet, ip-xx  Container ingress-controller failed liveness probe, will be restarted
  Normal   Started    6s (x2 over 38s)  kubelet, ip-xx  Started container ingress-controller
`

Here is what I have tried so far:
1. Change the ports on liveness and readiness
2. provided a public IP to the loadbalancer 
3. increased the timeouts and failure thresholds

Attached is the file modified yaml file. 

Pl. help. Also let pl let me know if the earlier version is better and stable in this regard

[all-in-one-dbless.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4526231/all-in-one-dbless.txt)

**Comment by Reefay** [comment] 2020-04-24 02:22
> Having the same issue via `kubectl apply -f https://bit.ly/kong-ingress-dbless`
> 
> here is the describe output on the pod:
> 
> `
> Name: ingress-kong-84647f7f8f-z4c62
> Namespace: kong
> Priority: 0
> Node: ip-xx/xx
> Start Time: Fri, 24 Apr 2020 01:48:46 +0000
> Labels: app=ingress-kong
> pod-template-hash=84647f7f8f
> Annotations: kuma.io/gateway: enabled
> prometheus.io/port: 9542
> prometheus.io/scrape: true
> traffic.sidecar.istio.io/includeInboundPorts:
> Status: Running
> IP: 10.244.4.13
> IPs:
> IP: 10.244.4.13
> Controlled By: ReplicaSet/ingress-kong-84647f7f8f
> Containers:
> proxy:
> Container ID: docker://c4edea5779c5f2c0d13e5f59cdc7e8f28ee664ad6c4cb7b94f72c6a56a407184
> Image: kong:2.0
> Image ID: docker-pullable://kong@sha256:f7a2bb6ae3baf60e3ca0d6ba5f83ebe3caf64fe8b6aa8dd6a5d3df16a22775c2
> Ports: 8000/TCP, 8443/TCP, 9542/TCP
> Host Ports: 0/TCP, 0/TCP, 0/TCP
> State: Running
> Started: Fri, 24 Apr 2020 01:48:47 +0000
> Ready: True
> Restart Count: 0
> Liveness: http-get http://:30010/health delay=10s timeout=2s period=10s #success=1 #failure=5
> Readiness: http-get http://:30010/health delay=15s timeout=3s period=10s #success=1 #failure=5
> Environment:
> KONG_DATABASE: off
> KONG_NGINX_WORKER_PROCESSES: 1
> KONG_NGINX_HTTP_INCLUDE: /kong/servers.conf
> KONG_ADMIN_ACCESS_LOG: /dev/stdout
> KONG_ADMIN_ERROR_LOG: /dev/stderr
> KONG_ADMIN_LISTEN: 127.0.0.1:8444 ssl
> KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl http2
> Mounts:
> /kong from kong-server-blocks (rw)
> /var/run/secrets/kubernetes.io/serviceaccount from kong-serviceaccount-token-f684p (ro)
> ingress-controller:
> Container ID: docker://b8309bf9fe47258a5dec6b52e7b3ac0d925d6a8866b2795e3647093124a91bfa
> Image: kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.8.1
> Image ID: docker-pullable://kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller@sha256:c7ccb6600d166a4986a30decf8a2db06161240b77e745de25ec8ce459a6570fa
> Port: 8080/TCP
> Host Port: 0/TCP
> Args:
> /kong-ingress-controller
> --kong-admin-url=https://localhost:8444
> --admin-tls-skip-verify
> --publish-service=kong/kong-proxy
> State: Running
> Started: Fri, 24 Apr 2020 01:49:19 +0000
> Last State: Terminated
> Reason: Error
> Exit Code: 255
> Started: Fri, 24 Apr 2020 01:48:47 +0000
> Finished: Fri, 24 Apr 2020 01:49:17 +0000
> Ready: False
> Restart Count: 1
> Liveness: http-get http://:30012/healthz delay=5s timeout=1s period=10s #success=1 #failure=3
> Readiness: http-get http://:30012/healthz delay=5s timeout=1s period=10s #success=1 #failure=3
> Environment:
> POD_NAME: ingress-kong-84647f7f8f-z4c62 (v1:metadata.name)
> POD_NAMESPACE: kong (v1:metadata.namespace)
> Mounts:
> /var/run/secrets/kubernetes.io/serviceaccount from kong-serviceaccount-token-f684p (ro)
> Conditions:
> Type Status
> Initialized True
> Ready False
> ContainersReady False
> PodScheduled True
> Volumes:
> kong-server-blocks:
> Type: ConfigMap (a volume populated by a ConfigMap)
> Name: kong-server-blocks
> Optional: false
> kong-serviceaccount-token-f684p:
> Type: Secret (a volume populated by a Secret)
> SecretName: kong-servi
> Optional: false
> QoS Class: BestEffort
> Node-Selectors:
> Tolerations: node.kubernetes.io/not-ready:NoExecute for 300s
> node.kubernetes.io/unreachable:NoExecute for 300s
> Events:
> Type Reason Age From Message
> 
> Normal Scheduled default-scheduler Successfully assigned kong/ingress-kong-84647f7f8f-z4c62 to ip-xx
> Normal Pulled 38s kubelet, ip-xx Container image "kong:2.0" already present on machine
> Normal Created 38s kubelet, ip-xx Created container proxy
> Normal Started 38s kubelet, ip-xx Started container proxy
> Warning Unhealthy 25s kubelet, ip-xx Liveness probe failed: Get http://10.244.4.13:30010/health: dial tcp 10.244.4.13:30010: connect: connection refused
> Warning Unhealthy 9s (x3 over 29s) kubelet, ip-xx Readiness probe failed: Get http://10.244.4.13:30012/healthz: dial tcp 10.244.4.13:30012: connect: connection refused
> Normal Pulled 7s (x2 over 38s) kubelet, ip-xx Container image "kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.8.1" already present on machine
> Normal Created 7s (x2 over 38s) kubelet, ip-xx Created container ingress-controller
> Warning Unhealthy 7s (x3 over 27s) kubelet, ip-xx Liveness probe failed: Get http://10.244.4.13:30012/healthz: dial tcp 10.244.4.13:30012: connect: connection refused
> Normal Killing 7s kubelet, ip-xx Container ingress-controller failed liveness probe, will be restarted
> Normal Started 6s (x2 over 38s) kubelet, ip-xx Started container ingress-controller
> `
> 
> Here is what I have tried so far:
> 
> 1. Change the ports on liveness and readiness
> 2. provided a public IP to the loadbalancer
> 3. increased the timeouts and failure thresholds
> 
> Attached is the file modified yaml file.
> 
> Pl. help. Also let pl let me know if the earlier version is better and stable in this regard
> 
> [all-in-one-dbless.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4526231/all-in-one-dbless.txt)

Oh good. It wasn't just me.

**Comment by Reefay** [comment] 2020-04-24 02:23
I really want to use Kong. I hope this can be fixed.

**Comment by rainest** [comment] 2020-04-24 17:20
@rlpatrao what do the controller container logs show in your case? Your issue should be different, since the admin URL is being passed via an argument rather than the environment variable, and looks correct at least from the perspective of `kubectl describe`.

**Comment by hbagdi** [comment] 2020-04-28 21:36
@Reefay ping.

**Comment by Reefay** [comment] 2020-04-28 21:46
> @Reefay ping.

What can I do for you?

**Comment by rlpatrao** [comment] 2020-04-28 21:48
Reefay, 

I re-installed K8S and Kong Ingress Controller - now things are working fine. 

Thanks,
Rajesh

**Comment by hbagdi** [comment] 2020-05-09 00:45
Is this still an issue?

**Comment by Reefay** [comment] 2020-05-09 00:51
> Is this still an issue?

I can't reinstall my platform as we're in active development. If you'd like to close this that's fine. I still can't get it running in my cluster.

**Comment by hbagdi** [comment] 2020-05-11 15:38
I don't like closing such issues which highlight that there might be a shortcoming in the product but we don't have any way to proceed further.
But, there is no way forward here either. If you run into this again, please do not hesitate in re-opening this issue or filling a new one.

**Closed by hbagdi** 2020-05-11 15:38 UTC
Labels: pending author feedback
