### ISSUE TITLE
Validating webhook denies request without explanation

### ISSUE THREAD

**Issue by agaffney** [Kong/kubernetes-ingress-controller#1783] opened 2021-08-31 19:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With Kong v2.3.3 and ingress-controller v1.3.1 deployed with the helm chart (v2.2.0), the validating webhook denies requests from the EKS API with a HTTP 400 error. This is on EKS 1.18/1.19.

This started happening when upgrading the helm chart (from v1.9.0) and the ingress-controller (from v0.9.1), but it's not clear which one actually caused it. We cannot easily regress these changes to try to determine which one it was.

```
$ kubectl edit kongplugin -n deploy-example kong-ingress-web-my-application-endpoint2-keycloak
error: kongplugins.configuration.konghq.com "kong-ingress-web-my-application-endpoint2-keycloak" could not be patched: admission webhook "validations.kong.konghq.com" denied the request without explanation
```

From EKS API server:

```
W0831 19:02:17.305040       1 dispatcher.go:142] rejected by webhook "validations.kong.konghq.com": &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"admission webhook \"validations.kong.konghq.com\" denied the request without explanation", Reason:"", Details:(*v1.StatusDetails)(nil), Code:400}}
```

There are no relevant logs from the ingress-controller when this occurs.

### Expected Behavior

It should validate the resource, or at least provide a useful error message.

### Steps To Reproduce

Create a fresh cluster using `k3d` (but it should work with whatever you want to use):

```
$ k3d cluster create
```

Helm values file (it may be reproducible with less than this, but this is already pared down from our actual use case):

```
admin:
  enabled: true
image:
  pullPolicy: Always
  tag: 2.3.3
ingressController:
  admissionWebhook:
    enabled: true
  image:
    tag: 1.3.1
  installCRDs: false
proxy:
  type: NodePort
replicaCount: 1
```

Install helm release:

```
$ helm repo add kong https://charts.konghq.com
"kong" has been added to your repositories
$ helm install kong kong/kong --version 2.2.0 -f /tmp/kong-ingress-values.yaml
```

Try to apply a `KongPlugin` resource:

```
$ cat /tmp/kong-ingress-plugin-test.yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: kong-global-config-ping-endpoint-request-termination
plugin: request-termination
config:
  status_code: 200
  message: "PONG"
$ kubectl apply -f /tmp/kong-ingress-plugin-test.yaml
Error from server: error when creating "/tmp/kong-ingress-plugin-test.yaml": admission webhook "validations.kong.konghq.com" denied the request without explanation
```

### Kong Ingress Controller version

```shell
v1.3.1
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.14", GitCommit:"0fd2b5afdfe3134d6e1531365fdb37dd11f54d1c", GitTreeState:"clean", BuildDate:"2021-08-11T18:07:41Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by agaffney** [comment] 2021-09-02 19:50
I have updated the description above with a test case that reproduces this problem.

**Comment by agaffney** [comment] 2021-09-02 19:51
As a side note, this only seems to happen with `KongPlugin` and not `KongClusterPlugin`

**Comment by ced0ps** [comment] 2021-09-07 11:23
Encountered the same issue. Downgrading kong-ingress-controller to 1.2 resolved it.
Issue was encountered with all versions of 1.3.x.

**Comment by mflendrich** [comment] 2021-09-07 13:12
Thank you for the report. I'll try to reproduce and debug, and get back to you with some information.

**Comment by zystem** [comment] 2021-09-10 09:16
Same error on kops with ingress-controller v1.3.x `cannot patch "abc-rate-limiting" with kind KongPlugin: admission webhook "validations.kong.konghq.com" denied the request without explanation` on both Kong v2.3.0 and Kong v2.5.0 and on both Chart v2.3.0 and Chart v1.13.0

**Comment by ulyssescb** [comment] 2021-09-21 18:16
Same error with kops(kubernetes version 1.17.17) with ingress controller 1.3.2.

`admission webhook "validations.kong.konghq.com" denied the request without explanation` when applying a CORS plugin.

**Comment by rainest** [comment] 2021-09-30 23:32
Duplicate of issue fixed by https://github.com/Kong/go-kong/pull/81. https://github.com/Kong/kubernetes-ingress-controller/pull/1887 to pull that in and release.

**Comment by rainest** [comment] 2021-10-01 00:21
Released https://github.com/Kong/kubernetes-ingress-controller/releases/tag/v1.3.3 with the upstream fix for this. Please let us know if there's still an issue and we'll review if needed.

**Closed by rainest** 2021-10-01 00:21 UTC
Labels: bug, needs investigation, severity/high
