### ISSUE TITLE
SNI issue with different certificates

### ISSUE THREAD

**Issue by elkh510** [Kong/kubernetes-ingress-controller#544] opened 2020-02-18 12:49 UTC
hi,
Below is an example of configuration, in which we get an error:
environments:
> Image of "proxy":
> kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:1.3.0.1-alpine
> Image of "ingress-controller":
> kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.7.1
> Image of "wait-for-migrations":
> kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:1.3.0.1-alpine

We have 2 namespace (in each 2 ingresses):
namespace test1
- ingress that directed to test1.example.com

namespace test2
- ingress that directed to test2.example.com

We also have the certificates for test1.example.com and test2.example.com

We configure ingresses in the namespaces as follows (an example is given only for test1):

```
Setup HTTPS redirect
kind: KongIngress
metadata:
    name: https-only
route:
  protocols:
  - https
  https_redirect_status_code: 302
```
Setup ingress is directed to test1.example.com:
```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: test1
  annotations:
    kubernetes.io/ingress.class: kong
    configuration.konghq.com: https-only
spec:
  tls:
    - hosts:
        - test1.example.com
      secretName: certificate-for-test1-example-com
  rules:
    - host: test1.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: test1
              servicePort: 80
```

After few hours we getting  in logs  errors:
```
I0213 03:00:08.186992       1 kong.go:57] no configuration change, skipping sync to Kong
I0213 03:00:11.510922       1 kong.go:57] no configuration change, skipping sync to Kong
E0213 03:00:18.706342       1 controller.go:119] unexpected failure updating Kong configuration: 
2 errors occurred:
	while processing event: {Create} failed: 400 Bad Request {"message":"schema violation (snis: test2.shelby.example.com already associated with existing certificate '9fea2a42-a17d-482b-9d35-2a17e708de23')","name":"schema violation","fields":{"snis":"test2.shelby.example.com already associated with existing certificate '9fea2a42-a17d-482b-9d35-2a17e708de23'"},"code":2}
	while processing event: {Create} failed: 400 Bad Request {"message":"schema violation (snis: test1.shelby.example.com already associated with existing certificate '4028367c-eaa7-44de-989c-141182546f53')","name":"schema violation","fields":{"snis":"test1.shelby.example.com already associated with existing certificate '4028367c-eaa7-44de-989c-141182546f53'"},"code":2}
```

**Comment by hbagdi** [comment] 2020-02-18 17:34
This is a duplicate of https://github.com/Kong/kubernetes-ingress-controller/issues/524

**Closed by hbagdi** 2020-02-18 17:34 UTC

**Comment by hbagdi** [comment] 2020-02-19 16:00
Are the cert-key for test1 and test2 same or different? Are you using a wildcard certificate?
