### ISSUE TITLE
Test Request: Kong Gateway EE version 3.4.3.2-rc1

### ISSUE THREAD

**Issue by outsinre** [Kong/kubernetes-ingress-controller#5370] opened 2023-12-20 02:58 UTC
### What component needs testing with KIC?

Kong Gateway EE

### Container image

docker pull kong/kong-gateway-dev:3.4.3.2-rc1

**Comment by pmalek** [comment] 2023-12-20 11:47
The GKE related failure will be fixed when we use https://github.com/Kong/kubernetes-testing-framework/pull/911 in KIC tests.

The other failures seem to be caused by https://github.com/Kong/kubernetes-ingress-controller/issues/5373.

We'll rerun when the above get fixed.

**Comment by pmalek** [comment] 2023-12-20 14:16
https://github.com/Kong/kubernetes-testing-framework/pull/911 has been solved.

Remains to be fixed: https://github.com/Kong/kubernetes-ingress-controller/issues/5373.

**Comment by outsinre** [comment] 2023-12-21 02:32
@pmalek has this test passed? I find "has been resolved".

**Closed** 2023-12-21 09:16 UTC

**Comment by pmalek** [comment] 2023-12-21 09:50
@tao12345666333 rerun the tests and those passed now @outsinre
