### ISSUE TITLE
Helm Installation Failed for Kong with "i/o timeout" Error

### ISSUE THREAD

**Issue by sahilinfoviz** [Kong/kubernetes-ingress-controller#6550] opened 2024-10-15 11:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I do 
`helm install kong kong/kong --namespace dev-backend -f values.yaml --timeout 10m`
I got
`Error: INSTALLATION FAILED: Get "https://github.com/Kong/charts/releases/download/kong-2.42.0/kong-2.42.0.tgz": dial tcp: lookup github.com on 127.0.0.53:53: read udp 127.0.0.1:50228->127.0.0.53:53: i/o timeout`

### Expected Behavior

I am expecting it to start kong sucessfully. 

### Steps To Reproduce

```markdown
Steps Followed:
1. Create the values.yaml for Kong Configuration: You prepared a values.yaml file for installing Kong in DB-less mode, which would specify the necessary configurations for the Kong gateway.
my values.yaml include

# values.yaml for Kong installation in DB-less mode

dbmode: off  # DB-less mode
image:
  repository: kong
  tag: "3.4"  # Adjust the version as necessary

ingressController:
  enabled: true
  installCRDs: false  # CRDs are already installed

proxy:
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8000
  tls:
    enabled: false

admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
  tls:
    enabled: false

env:
  database: "off"  # Disable database, enable DB-less mode
  declarative_config: "/var/kong/kong.yml"

replicaCount: 1

2. Created a kong.yml file for request forwarding

my file content is as below

# kong.yml for DB-less configuration

_format_version: "3.0"
services:
  - name: nodejs-demo
    url: http://nodejs-demo-service.dev-backend.svc.cluster.local:3000  # Node.js service in Kubernetes
    routes:
      - name: nodejs-demo-route
        paths:
          - /nodejs-demo  # Route path to match
```

### Kubernetes version

```shell
Client Version: v1.30.5+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.5+k3s1
```

### Anything else?

I'm encountering an issue while trying to install Kong using Helm. The installation fails with the following error:
`Error: INSTALLATION FAILED: Get "https://github.com/Kong/charts/releases/download/kong-2.42.0/kong-2.42.0.tgz": dial tcp: lookup github.com on 127.0.0.53:53: read udp 127.0.0.1:50228->127.0.0.53:53: i/o timeout
`

**Comment by pmalek** [comment] 2024-10-17 09:17
Hi @sahilinfoviz 👋 

This looks like a network issue on your side. You can try accessing the .tgz file that helm complains about in https://github.com/Kong/charts/releases/tag/kong-2.42.0. It is available and I can confirm it works on my end.

You can also retry to check if this was fixed on your end. There's nothing we can do on our side to fix / change this.

Hope this clears things up.

**Closed by pmalek** 2024-10-17 09:17 UTC
Labels: bug
