### ISSUE TITLE
TLS verification feature user-acceptance testing

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#6633] opened 2024-11-07 07:42 UTC
This issue aims to cover the upstream TLS verification feature both for Gateway API policy and Ingress annotations.

### Acceptance criteria 
- [x] Somebody who wasn't involved directly in the feature development has verified the guide works as expected
- [x] The same person tried to break the feature triggering edge-case scenarios

**Comment by lahabana** [comment] 2024-11-13 09:22
Blocked on the rest of the implementation

**Comment by pmalek** [comment] 2024-12-13 16:31
Performed some tests and everything seems to work.

Created #6837 to enqueue `BackendTLSPolicy` after referenced `ConfigMap` changes

Also experienced the delay in which the config gets applied as noted by Charly in https://github.com/Kong/docs.konghq.com/pull/8201#discussion_r1883697522. 

Looked around and it seems that this is caused by `upstream_keepalive_idle_timeout` ( which is 60 by default). I've done some non scientific tests locally and it proved my thesis.

Added a note about that in https://github.com/Kong/docs.konghq.com/commit/25efd421af37161548dea6914a936f09ab52dfe3.

When #6837 merged this can be closed.

**Closed** 2024-12-13 16:46 UTC
Labels: area/tests, release/required
