### ISSUE TITLE
ADDRESS is not coming up in my ingress

### ISSUE THREAD

**Issue by jaikratsinghtariyal** [Kong/kubernetes-ingress-controller#1858] opened 2021-09-23 18:07 UTC
I am trying to setup kong as my ingress controller in my Kuma service mesh POC.

Here is my deployment.yaml and ingress.yaml

1. https://github.com/jaikratsinghtariyal/spring-boot-k8s/blob/main/deployment.yaml
2. https://github.com/jaikratsinghtariyal/spring-boot-k8s/blob/main/ingress-deployment.yaml

Below are the logs from my ingress-controller container in my ingress-kong pod.

```
2021-09-23T17:55:38.352Z | E0923 17:55:38.351702 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1beta1.TCPIngress: failed to list *v1beta1.TCPIngress: tcpingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "tcpingresses" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:55:38.533Z | E0923 17:55:38.532740 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:55:46.762Z | E0923 17:55:46.761819 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongPlugin: failed to list *v1.KongPlugin: kongplugins.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongplugins" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:55:48.302Z | E0923 17:55:48.302270 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:55:50.686Z | E0923 17:55:50.685528 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Ingress: failed to list *v1.Ingress: ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "ingresses" in API group "networking.k8s.io" at the cluster scope
2021-09-23T17:55:50.895Z | E0923 17:55:50.894700 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongIngress: failed to list *v1.KongIngress: kongingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongingresses" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:55:53.042Z | E0923 17:55:53.042558 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongClusterPlugin: failed to list *v1.KongClusterPlugin: kongclusterplugins.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongclusterplugins" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:55:59.600Z | E0923 17:55:59.600385 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongConsumer: failed to list *v1.KongConsumer: kongconsumers.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongconsumers" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:56:03.104Z | E0923 17:56:03.104143 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:56:05.691Z | E0923 17:56:05.689466 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "secrets" in API group "" at the cluster scope
2021-09-23T17:56:13.737Z | E0923 17:56:13.736482 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:56:15.677Z | E0923 17:56:15.676957 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "endpoints" in API group "" at the cluster scope
2021-09-23T17:56:19.693Z | E0923 17:56:19.692793 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "services" in API group "" at the cluster scope
2021-09-23T17:56:22.266Z | E0923 17:56:22.266029 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1beta1.TCPIngress: failed to list *v1beta1.TCPIngress: tcpingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "tcpingresses" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:56:23.878Z | E0923 17:56:23.877816 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:56:30.118Z | E0923 17:56:30.117653 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongIngress: failed to list *v1.KongIngress: kongingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongingresses" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:56:31.241Z | E0923 17:56:31.240581 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Ingress: failed to list *v1.Ingress: ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "ingresses" in API group "networking.k8s.io" at the cluster scope
2021-09-23T17:56:36.752Z | E0923 17:56:36.752327 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongClusterPlugin: failed to list *v1.KongClusterPlugin: kongclusterplugins.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongclusterplugins" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:56:39.158Z | E0923 17:56:39.158256 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongPlugin: failed to list *v1.KongPlugin: kongplugins.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongplugins" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:56:40.285Z | E0923 17:56:40.284882 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:56:50.400Z | E0923 17:56:50.400349 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:56:52.180Z | E0923 17:56:52.180259 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "secrets" in API group "" at the cluster scope
2021-09-23T17:56:57.964Z | E0923 17:56:57.963910 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongConsumer: failed to list *v1.KongConsumer: kongconsumers.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongconsumers" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:57:03.556Z | E0923 17:57:03.556283 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1beta1.TCPIngress: failed to list *v1beta1.TCPIngress: tcpingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "tcpingresses" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:57:04.217Z | E0923 17:57:04.216882 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:57:07.090Z | E0923 17:57:07.090687 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "endpoints" in API group "" at the cluster scope
2021-09-23T17:57:18.590Z | E0923 17:57:18.590361 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:57:18.689Z | E0923 17:57:18.689196 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongIngress: failed to list *v1.KongIngress: kongingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongingresses" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:57:19.008Z | E0923 17:57:19.008695 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Ingress: failed to list *v1.Ingress: ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "ingresses" in API group "networking.k8s.io" at the cluster scope
2021-09-23T17:57:19.457Z | E0923 17:57:19.455794 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "services" in API group "" at the cluster scope
2021-09-23T17:57:19.929Z | E0923 17:57:19.928812 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongClusterPlugin: failed to list *v1.KongClusterPlugin: kongclusterplugins.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongclusterplugins" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:57:21.815Z | E0923 17:57:21.814759 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongPlugin: failed to list *v1.KongPlugin: kongplugins.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongplugins" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:57:28.572Z | E0923 17:57:28.571780 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "secrets" in API group "" at the cluster scope
2021-09-23T17:57:34.334Z | E0923 17:57:34.334019 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:57:44.244Z | E0923 17:57:44.244337 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1beta1.TCPIngress: failed to list *v1beta1.TCPIngress: tcpingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "tcpingresses" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:57:44.479Z | E0923 17:57:44.479534 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:57:47.891Z | E0923 17:57:47.890811 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongConsumer: failed to list *v1.KongConsumer: kongconsumers.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongconsumers" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:57:52.014Z | E0923 17:57:52.013989 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "endpoints" in API group "" at the cluster scope
2021-09-23T17:57:52.208Z | E0923 17:57:52.208547 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "services" in API group "" at the cluster scope
2021-09-23T17:57:54.238Z | E0923 17:57:54.238285 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongClusterPlugin: failed to list *v1.KongClusterPlugin: kongclusterplugins.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongclusterplugins" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:58:00.129Z | E0923 17:58:00.129175 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:58:08.593Z | E0923 17:58:08.589449 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Ingress: failed to list *v1.Ingress: ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "ingresses" in API group "networking.k8s.io" at the cluster scope
2021-09-23T17:58:10.498Z | E0923 17:58:10.497968 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongIngress: failed to list *v1.KongIngress: kongingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongingresses" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:58:15.531Z | E0923 17:58:15.531290 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:58:16.480Z | E0923 17:58:16.476952 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongPlugin: failed to list *v1.KongPlugin: kongplugins.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongplugins" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:58:22.639Z | E0923 17:58:22.639382 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "services" in API group "" at the cluster scope
2021-09-23T17:58:23.537Z | E0923 17:58:23.537708 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "secrets" in API group "" at the cluster scope
2021-09-23T17:58:26.860Z | E0923 17:58:26.860252 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1beta1.TCPIngress: failed to list *v1beta1.TCPIngress: tcpingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "tcpingresses" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:58:27.308Z | E0923 17:58:27.308407 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongConsumer: failed to list *v1.KongConsumer: kongconsumers.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongconsumers" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:58:31.707Z | E0923 17:58:31.707647 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:58:41.485Z | E0923 17:58:41.484717 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "endpoints" in API group "" at the cluster scope
2021-09-23T17:58:42.471Z | E0923 17:58:42.470373 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Ingress: failed to list *v1.Ingress: ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "ingresses" in API group "networking.k8s.io" at the cluster scope
2021-09-23T17:58:43.384Z | E0923 17:58:43.384076 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongClusterPlugin: failed to list *v1.KongClusterPlugin: kongclusterplugins.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongclusterplugins" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:58:47.550Z | E0923 17:58:47.549788 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:58:55.359Z | E0923 17:58:55.358779 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "secrets" in API group "" at the cluster scope
2021-09-23T17:59:01.242Z | E0923 17:59:01.242191 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongIngress: failed to list *v1.KongIngress: kongingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongingresses" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:59:03.640Z | E0923 17:59:03.639697 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
2021-09-23T17:59:05.012Z | E0923 17:59:05.012154 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "services" in API group "" at the cluster scope
2021-09-23T17:59:10.936Z | E0923 17:59:10.936034 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.KongPlugin: failed to list *v1.KongPlugin: kongplugins.configuration.konghq.com is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot list resource "kongplugins" in API group "configuration.konghq.com" at the cluster scope
2021-09-23T17:59:11.586Z | E0923 17:59:11.585977 1 leaderelection.go:325] error retrieving resource lock kuma-gateway/ingress-controller-leader-kong: configmaps "ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:kuma-gateway:kong-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "kuma-gateway"
```

**Comment by jaikratsinghtariyal** [comment] 2021-09-24 10:25
Any one?

**Comment by johnharris85** [comment] 2021-09-26 16:55
Looks like an RBAC issue. What RBAC permissions and service accounts do you have setup in the cluster relating to these components?

**Comment by jaikratsinghtariyal** [comment] 2021-09-27 05:37
Thanks for reply @johnharris85 .... but the issue got resolved after firing two below commands.

1. minikube addons enable ingress  
2. minikube tunnel 

I am using minikube and in there something like above need to be done.

**Comment by shaneutt** [comment] 2021-09-30 14:47
This appears to be a duplicate of an existing discussion:

https://github.com/Kong/kubernetes-ingress-controller/discussions/1854

Closing it as a duplicate but let us know if there's something more to do here.

**Closed by shaneutt** 2021-09-30 14:47 UTC
