### ISSUE TITLE
kong ingress controller get error when targets more than 3

### ISSUE THREAD

**Issue by yaoice** [Kong/kubernetes-ingress-controller#643] opened 2020-05-07 14:06 UTC
### Summary
I use kong and kubernetes ingress controller in arm64v8 environment, but I encountered a strange problem, kubernetes-ingress-controller failed to send post to kong admin api. At first, I thought it was a kubernetes-ingress-controller bug, and later I found that it was a kong problem. 

kong ingress controller error message:
> E0507 13:35:46.952831       1 controller.go:119] unexpected failure updating Kong configuration: 
> posting new config to /config: making HTTP reqeust: Post http://localhost:8001/config?check_hash=1: EOF
> W0507 13:35:46.952869       1 queue.go:112] requeuing tcnp/dashboard, err posting new config to /config: making HTTP reqeust: Post http://localhost:8001/config?check_hash=1: EOF

### Steps To Reproduce
1. Use [all-in-one-dbless.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/0.7.1/deploy/single/all-in-one-dbless.yaml) to Install kubernetes kong ingress controller
2. Run an deployment with ingress in k8s
3. Scale deployment replicas to 5, then kubernetes ingress controller will get error
4. Scale deployment replicas to 3, wait an while, kubernetes ingress controller will get back to ok

### Additional Details & Logs
Kubernetes version: 1.14.6
Kong version 1.4.3
kubernetes-ingress-controller version: 0.7.1
Kong debug-level startup logs ($ kong start --vv)
Kong error logs ( It seems that none error message) [log link](http://paste.openstack.org/show/793275/)
Kubernetes-ingress-controller error logs: [log link](http://paste.openstack.org/show/793276/)
Json post to kong admin api: [JSON](http://paste.openstack.org/show/793279/)
Operating system: Ubuntu 9.1.0-2ubuntu2~16.04
Arch: arm64v8

**Comment by yaoice** [comment] 2020-05-08 09:55
@hbagdi Please help to check

**Comment by hbagdi** [comment] 2020-05-08 17:22
Can you upgrade Kong to 2.0.4?
This seems a problem with balancer worker events.

@Tieske Can you take a look at the logs?

**Comment by hbagdi** [comment] 2020-05-08 22:54
Duplicate of https://github.com/Kong/kong/issues/5869

**Closed by hbagdi** 2020-05-08 22:54 UTC
