### ISSUE TITLE
<Feature request> Ability to configure a default KongIngress resource

### ISSUE THREAD

**Issue by bspaans** [Kong/kubernetes-ingress-controller#162] opened 2018-10-15 01:31 UTC
The documentation mentions two ways to associate an Ingress with a KongIngress resource (deploying with the same name and annotationing), but it would be nice if there was a third option which would allow you to configure a default KongIngress configuration.

**Comment by hbagdi** [comment] 2018-10-15 20:12
@bspaans 
I see that you're trying to use certbot with Kong.

You could currently use the annotation driven method to apply a single KongIngress resource to your select Ingress specs.
Have you tried using the annotation driven method?

I'm not sure if Ingress spec of Kubernetes specifies what to  do with `Host` header when proxying the request upstream and hence we're relying on the default behavior of Kong.

**Comment by bspaans** [comment] 2018-10-17 11:14
Thanks for your reply @hbagdi. I am using KongIngress references myself for my own Ingress resources, but cert-manager creates a new Ingress resource to handle the ACME http01 validation, and that Ingress resource doesn't have this annotation (the issue I raised with them asks to make that configurable) and seems to rely on the default behaviour of the nginx controller. For reference here's an example of my Ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: escapekit-user-service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    configuration.konghq.com: global-kong-ingress-rules
    certmanager.k8s.io/issuer: letsencrypt-escapekit
spec:
  tls: 
  - hosts:
    - "www.example.com"
    secretName: escapekit-cert
  rules:
  - host: "www.example.com"
    http:
      paths:
      - path: /api/v1/auth
        backend:
          serviceName: user-service
          servicePort: http
```

The Ingress spec does not prescribe what to do with the Host header as far as I'm aware, but I was under the impression that the Kong controller would be a drop-in replacement for the nginx controller, which does seem to default to forwarding the Host header (see https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-nginx-upstream-vhost)

**Comment by hbagdi** [comment] 2018-12-06 04:13
Hi @bspaans,

Sorry for the late response here.

I see that you opened up https://github.com/jetstack/cert-manager/issues/958 for this purpose.

I do understand that this is a problem for you and we would like to help out but the proposed solution can create more problems rather.

Resource definitions should be as declarative as possible and be extensible as well. In my analysis, adding another resource to provide defaults seems like a bigger hammer than necessary to solve this problem.

Having said that, we would like to solve this issue and definitely want cert-manager and Kong to work together.

**Comment by dcherniv** [comment] 2018-12-21 19:05
@hbagdi i second this. Just ran into this issue myself. Is there a workaround?

**Comment by dongtianyi** [comment] 2019-01-02 07:02
@hbagdi  I have the same issue. 
preserve_host default to true. 
Otherwise, every ingress modification, I must manually change it.
workaround for now ?
Thanks!

**Comment by stackedsax** [comment] 2019-01-14 04:18
Just thought I'd point out: 

- https://github.com/jetstack/cert-manager/issues/1097

Which is a response to @bspaans original certman issue, https://github.com/jetstack/cert-manager/issues/958

**Comment by hbagdi** [comment] 2019-03-04 20:05
Blocked on https://github.com/jetstack/cert-manager/issues/1097

**Comment by thedumbtechguy** [comment] 2019-03-11 15:41
Do we have any workaround for this?

I am considering installing the nginx ingress just for this, but I really don't want to.

**Comment by ollystephens** [comment] 2019-03-19 11:17
I wrote a small helper as a workaround for this problem.
https://github.com/ollystephens/acme-kong-kube-helper
Hopefully it won't be needed long-term, but is an alternative to modifying the core ingress controller codebase in the meantime.

**Comment by bgarcial** [comment] 2019-03-21 13:06
I've applied this `acme-kong-kube-helper` github.com/ollystephens/acme-kong-kube-helper in order to solve the `http01` validation problem in staging environment, and all it's works. 

When the `http01` validation to be performed, is necessary to use the `letsencrypt production` environment to get the `https` encryption. 

The problem is mainly that cert-manager have some problems to work with other ingress controllers to nginx (?). This helper is a temporal solution whereas cert-manager work in this feature to solve this https://github.com/jetstack/cert-manager/issues/1097 (?)

**Comment by gpabdo** [comment] 2019-04-17 02:32
How would setting `preserve_host: true` as default be a bad thing? This is how the Nginx ingress treats a request. I spent hours trying to trouble shoot this same issue for a MinIO deployment recently, and it would just fix this major issue with cert-manager.

- Just incase someone runs into this error deploying MinIO behind Kong again:
`The request signature we calculated does not match the signature you provided. Check your key and signing method.`

**Comment by hbagdi** [comment] 2019-04-17 02:42
`preserve_host` will be set to `true` by default starting with the next version of the Ingress Controller: https://github.com/Kong/kubernetes-ingress-controller/blob/next/internal/ingress/controller/parser/parser.go#L201

**Comment by gpabdo** [comment] 2019-04-17 03:03
Fantastic! This will be super helpful. 0.4.x?

**Comment by hbagdi** [comment] 2019-04-17 03:26
> 0.4.x?

Yes.

**Comment by hbagdi** [comment] 2019-05-09 01:11
An update here:
https://github.com/Kong/kubernetes-ingress-controller/pull/286 will fix the original problem that this issue was based on.

**Comment by hbagdi** [comment] 2019-07-02 20:10
Closing this as an alternate solution is now available.

**Closed by hbagdi** 2019-07-02 20:10 UTC
Labels: wontfix
