### ISSUE TITLE
kong not work in k8s

### ISSUE THREAD

**Issue by lnsane** [Kong/kubernetes-ingress-controller#1703] opened 2021-08-14 02:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm install new version k8s

using flannel in k8s

I'm install kubectl apply -f https://bit.ly/k4k8s

namespace/kong created
serviceaccount/kong-serviceaccount created
service/kong-proxy created
service/kong-validation-webhook created
deployment.apps/ingress-kong created
unable to recognize "https://bit.ly/k4k8s": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "https://bit.ly/k4k8s": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "https://bit.ly/k4k8s": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "https://bit.ly/k4k8s": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "https://bit.ly/k4k8s": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "https://bit.ly/k4k8s": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
unable to recognize "https://bit.ly/k4k8s": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"

![1628907651(1)](https://user-images.githubusercontent.com/20310872/129431555-14481c2d-4e22-427d-92a8-35e95640f905.png)

![image](https://user-images.githubusercontent.com/20310872/129431658-dceab3b0-91c3-4f73-b73d-3bc37f3c9285.png)

### Steps To Reproduce

```markdown
sudo kubeadm init  --pod-network-cidr=100.10.0.0/8

kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

kubectl apply -f https://bit.ly/k4k8s
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by MinhDuc010194** [comment] 2021-08-14 05:59
I have a similar issue when tried to install Kong. my kubectl version is v1.22.0. and I use calico network

**Comment by lnsane** [comment] 2021-08-14 07:37
The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of v1.22.

The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of v1.22.

The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of v1.22.

!!!!!!

**Comment by MinhDuc010194** [comment] 2021-08-14 10:48
I had to downgrade to v1.19 to install Kong and it works

Vào Th 7, 14 thg 8, 2021 vào lúc 14:37 王存露 ***@***.***> đã
viết:

**Comment by MinhDuc010194** [comment] 2021-08-14 10:50
I had downgraded to v1.19 to install Kong. it works.  maybe Kong has a problem with v1.22

**Comment by shaneutt** [comment] 2021-08-16 14:54
This relates to #1683 as we are currently working on support for the recently GA'd `v1.22` of Kubernetes which contains several backwards incompatible changes that need to be adjusted for.

Please note that #1683 will resolve this for the `v2.x` series of Kong Kubernetes Ingress Controllers, but the `v1.x` versions will be limited to a maximum Kubernetes version of `v1.21`.

For now I'm going to close this as a duplicate of #1683 and ask that we continue any relevant conversations in that issue, but if you feel I'm mistaken and feel that there's value in continuing a conversation here separate of that please feel free to re-open and let us know how we can assist you.

**Closed by shaneutt** 2021-08-16 14:54 UTC
Labels: bug
