### ISSUE TITLE
Omitting trailing slash results in 301 redirect to relevant Pod IP

### ISSUE THREAD

**Issue by sergerad** [Kong/kubernetes-ingress-controller#1440] opened 2021-06-16 22:44 UTC
### Summary

Kong proxy is redirecting traffic directly to a Pod's IP via `location` header in 301 redirect response to requests where trailing slash is omitted. Adding trailing slash results in no redirect, works fine.

E.g. location header `location: http://10.244.0.29/docs/`. That IP is cluster local.

**Kong Ingress controller version**

kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:1.2

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"c1ad2bc44e0c7f19a9db0879f7182ff556a8e5b4", GitTreeState:"clean", BuildDate:"2021-05-19T22:27:45Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider**: GKE

### What happened

Relevant proxy logs output:
```
125.239.198.205 - - [16/Jun/2021:22:43:23 +0000] "GET /docs HTTP/1.1" 301 134 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36"
```

Here is the Ingress YAML:
```
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/https-redirect-status-code: "301"
      konghq.com/preserve-host: "false"
      konghq.com/protocols: https
      konghq.com/strip-path: "false"
      kubernetes.io/ingress.class: kong
      kubernetes.io/tls-acme: "true"
...
  spec:
    rules:
    - host: deviceplane.com
      http:
        paths:
        - backend:
            serviceName: deviceplane-www
            servicePort: 80
          path: /
          pathType: ImplementationSpecific
    - host: www.deviceplane.com
      http:
        paths:
        - backend:
            serviceName: deviceplane-www
            servicePort: 80
          path: /
          pathType: ImplementationSpecific
    - host: downloads.deviceplane.com
      http:
        paths:
        - backend:
            serviceName: deviceplane-downloads
            servicePort: 80
          path: /
          pathType: ImplementationSpecific
    - host: cloud.deviceplane.com
      http:
        paths:
        - backend:
            serviceName: deviceplane
            servicePort: 80
          path: /
          pathType: ImplementationSpecific
```
Here is the KongIngress YAML (for timeouts):
```
apiVersion: v1
items:
- apiVersion: configuration.konghq.com/v1
  kind: KongIngress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"configuration.konghq.com/v1","kind":"KongIngress","metadata":{"annotations":{},"name":"deviceplane","namespace":"deviceplane"},"proxy":{"connect_timeout":60000,"read_timeout":60000,"write_timeout":60000}}
    creationTimestamp: "2021-06-02T05:49:07Z"
    name: deviceplane
    namespace: deviceplane
  proxy:
    connect_timeout: 60000
    read_timeout: 60000
    write_timeout: 60000
```

### Expected behavior

Expect no redirect at all. Or expect redirect to not aim at Pod IP but instead point to LB IP.

### Steps To Reproduce

1. Visit deviceplane.com/docs/ confirm success
2. Visit deviceplane.com/docs confirm failure

**Comment by shaneutt** [comment] 2022-03-22 20:07
Closing as stale. If anyone is still having this issue on a modern supported version of the ingress controller (2.2 is the latest at the time of writing) please do comment here and let us know what version you're experiencing this on and we'll be happy to re-open and re-assess.

**Comment by axelsean** [comment] 2022-05-05 22:29
I'm getting this on 2.8 of kong

My Ingress

`
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ams-ui                         # Looks like this and the kongIngress name have to match the service
  namespace: ams-kubernetes
  annotations:
    konghq.com/https-redirect-status-code: "302"
    konghq.com/methods: GET,POST,PUT
    konghq.com/preserve-host: "false"
    konghq.com/protocols: http
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /ams-ui/.*
            pathType: Prefix
            backend:
              service:
                name: ams-ui
                port:
                  number: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: ams-ui
  namespace: ams-kubernetes
upstream:
  healthchecks:
    active:
      healthy:
        http_statuses:
          - 200
          - 302
        interval: 5
        successes: 3
      http_path: /ams-ui/health
      type: http
      unhealthy:
        http_failures: 1
        interval: 5
`

![Screen Shot 2022-05-05 at 5 27 51 PM](https://user-images.githubusercontent.com/18721212/167035400-c1a06ac9-39a3-4713-b9f6-f8d254a98996.png)

**Comment by axelsean** [comment] 2022-05-05 22:54
I can reproduce this in a second way.   I have a Tomcat server with JSP pages, one request issues a redirect to another JSP, same result, the pod IP is used, this time I know the incoming request reached the Tomcat Pod

![Screen Shot 2022-05-05 at 5 52 23 PM](https://user-images.githubusercontent.com/18721212/167038933-e9c71866-a6b4-420f-9551-0dc05acfaf66.png)

**Comment by shaneutt** [comment] 2022-05-06 14:25
@axelsean I see that you posted using Kong Gateway 2.8, but I may have missed what ingress controller version you're running. Can you let me know which version of the KIC is deployed in this case?

**Comment by axelsean** [comment] 2022-05-06 19:58
The second issue I fixed by setting preserveHost on the route

**Comment by axelsean** [comment] 2022-05-06 21:14
KIC image is - kong/kubernetes-ingress-controller:2.3.1

From https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-postgres.yaml

**Comment by axelsean** [comment] 2022-05-09 14:55
@shaneutt Thx - If you need me to turn on debug logging I can easily do this - just let me know how

**Comment by shaneutt** [comment] 2022-05-09 15:15
You can do `--log-level debug` as a command line flag for the controller, or `CONTROLLER_LOG_LEVEL=debug` as an ENV var.

**Comment by axelsean** [comment] 2022-05-10 15:12
Turned that on for the ingress controller - doesn't seem to show anything - just this repeated:

**Comment by rainest** [comment] 2022-05-17 20:50
@axelsean your and the original issue likely stem from behavior of the upstream application. It likely expects configuration that indicates how it should generate URLs, and absent that configuration, will provide a best effort guess based on its listens (in this case, it is indeed listening on the Pod IP). Brief review suggests this might be handled by Tomcat's [Host](https://tomcat.apache.org/tomcat-8.0-doc/config/host.html) and [Context](https://tomcat.apache.org/tomcat-8.0-doc/config/context.html) configuration, but I'm not familiar with Tomcat and can't say for sure. I'll close this as such, but if you can replicate this with an [httpbin instance](https://github.com/istio/istio/blob/master/samples/httpbin/httpbin.yaml) or similar, please open a new issue.

Kong itself wouldn't be able to formulate this response since our only native in-proxy redirect functionality is for HTTP->HTTPS redirects, which wouldn't apply here (your Ingress is configured to be HTTP-only). You should be able to confirm that the redirect response is being forwarded from upstream by [using tcpdump](https://docs.konghq.com/kubernetes-ingress-controller/2.3.x/troubleshooting/#inspecting-network-traffic-with-a-tcpdump-sidecar) and filtering on the Pod IP with a single upstream application replica (maybe--see the other odd stuff section later).

Those responses, and other responses generated directly by Kong (e.g. the 404 no route response) will only include `X-Kong-Response-Latency` in response headers. If you're also seeing `X-Kong-Proxy-Latency`, your response is from upstream.

```
$ curl -sv http://192.168.16.0/httpbin               
*   Trying 192.168.16.0:80...
* Connected to 192.168.16.0 (192.168.16.0) port 80 (#0)
> GET /httpbin HTTP/1.1
> Host: 192.168.16.0
> User-Agent: curl/7.82.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 426 
< Date: Tue, 17 May 2022 20:43:21 GMT
< Content-Type: application/json; charset=utf-8
< Connection: keep-alive
< Connection: Upgrade
< Upgrade: TLS/1.2, HTTP/1.1
< Content-Length: 39
< X-Kong-Response-Latency: 0
< Server: kong/2.8.1
```

I used a slightly modified version of your Ingress ([1440_test.yaml.txt](https://github.com/Kong/kubernetes-ingress-controller/files/8711277/1440_test.yaml.txt)) to test this using another application: [1440_results.txt](https://github.com/Kong/kubernetes-ingress-controller/files/8711416/1440_results.txt). Note that I'm using `konghq.com/path: /anything` on the httpbin Service since you don't have `strip_path: true` set and httpbin won't recognize your application's paths.

There's something else odd going on where using `Prefix` shouldn't actually get you any response for `/ams-ui` with that Ingress because of the way our route generation works. The third `"/ams-ui/.*$","/ams-ui/.*/"` path set is what that will generate. `/ams-ui` will not match it and does return a 404 for me. You may have some other Ingress that's actually handling this (or an additional Kong instance--the 301 should appear in the access logs whether it came from Kong or upstream), but the general points about this redirect coming from upstream remain true:

```
13:17:46-0700 esenin $ curl -sk https://localhost:8999/routes | jq ".data[] | .paths"
[
  "/ams-ui-test2/.*"
]
[
  "/ams-ui-test3"
]
[
  "/ams-ui/.*$",
  "/ams-ui/.*/"
]
[
  "/ams-ui-test1$",
  "/ams-ui-test1/"
]
[
  "/httpbin"
]
```

You should not provide your own regular expressions with pathTypes other than `ImplementationSpecific`. We generate our own regexes to comply with the Ingress spec, and combining the two can result in unexpected effects (though I think it's harmless in this case). Both `Prefix` and `ImplementationSpecific` with non-regex paths should probably work for what you want here: Kong's default behavior is essentially the official `Prefix` with the caveat that we'll also match continued strings that aren't separated with a slash (e.g. the `/ams-ui-test3` will also match `/ams-ui-test3whatever` in addition to the official `Prefix` matches, `/ams-ui-test3`, `/ams-ui-test3/`, and `/ams-ui-test3/whatever`).

**Closed by rainest** 2022-05-17 20:50 UTC
Labels: bug, needs-triage, severity/medium

**Comment by axelsean** [comment] 2022-05-24 19:55
I wasn't seeing any error in the upstream, it was a simple nginx server with a React app - the redirect worked when we hit that application outside the kong environment

I also have a service ams-ui-metadata - so I need the trailing slash

Are these two what's needed ?

          - path: /ams-ui/
            pathType: Prefix

another ingress

          - path: /ams-ui-metadata/
            pathType: Prefix

**Comment by rainest** [comment] 2022-06-01 16:38
You want either `Exact` (`/ams-ui` and `/ams-ui/` only) or `ImplementationSpecific` (`/ams-ui` along with `/ams-ui/whatever`, `/ams-uiwhatever`, etc.). The `Prefix` spec excludes matches without the trailing slash.

**Comment by axelsean** [comment] 2022-06-13 19:00
Putting what I have here - for reference - I have this working now:

Used a Prefix for the version with / and exact for the without - passes the request to the service which then does the needed redirects

`  rules:
    - http:
        paths:
          - path: /ams-ui/.*
            pathType: Prefix
            backend:
              service:
                name: ams-ui
                port:
                  number: 80
          - path: /ams-ui
            pathType: Exact
            backend:
              service:
                name: ams-ui
                port:
                  number: 80
`
