### ISSUE TITLE
Group similar routes together

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2218] opened 2022-01-27 09:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Today KIC creates a `Route` object in Kong Admin API for each `spec.rules` entry in each `Ingress` resource.

This is suboptimal. It is possible to group ingress rules that only differ in `path` under one Kong `Route`.

### Proposed Solution

Across all ingresses ingested by `parser/translate` in one pass of `Build`, group similar ingress rules (also across Ingress resources) and make them a single `Route`.

The definition of "similar" is open, but it means at least:
- being equal except for `path`.

### Acceptance Criteria

- [ ] For multiple ingress rules (even in different Ingress resources) that only differ by path, KIC no longer creates separate `Route`s, but just one, with all the paths combined.

**Comment by shaneutt** [comment] 2022-05-16 21:29
Closing as a duplicate of #2490, as the newer issue has more people looking at it as it was shared around quite a bit recently.

**Closed by shaneutt** 2022-05-16 21:29 UTC
Labels: area/feature, severity/low, area/perf, nice-to-have
